### PR TITLE
Fix: fixed the treectx flaws in javamds and updated java/tests

### PR DESCRIPTION
**Pull request by zack-vii**
* jni will now use ctx whenever possible.
* Tree open and close operation carefully handle ctx
* memcheck is now satisfied.
* fixed MDSplus.MdsConnectionTest's mdsip spawn
Addresses issues pointed out in #1538
Includes PR #1862

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Review by AndreaRigoni — COMMENTED** [review]
Great now we got TAP for all java tests too !

**Comment by zack-vii** [comment]
Would you please review this pr?

**Review by AndreaRigoni — APPROVED** [review]
OK

**Pull request merged**
