### PR TITLE
Fix: cast rfa to Uint64 in python api

### PR DESCRIPTION
**Pull request by zack-vii**
addresses #1655

### CODE REVIEW

**Review by tfredian — COMMENTED** [review]
This may solve the problem of rfa causing an error but at least for some of the nci items there are advantages in returning MDSplus scalar types instead of native python types. It may be the only case where this is true is time_inserted which used to return a Uint64 type which has properties such as date and time. One might be able to create a Uint64 instance with the return value but since there is not much else an application might want to do with the time_inserted value there is no reason not to return a Uint64.

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
looks like an issue with mdstcpip
http://jenkins2.mdsplus.org/job/fc28/2752/
free(): invalid pointer
 ... again/still possibly when a connection is dropped.

http://jenkins2.mdsplus.org/job/fc28/2752/artifact/tests/64/python/MDSplus/tests/connectionUnitTest.log/*view*/

should not be related to this PR though

**Comment by zack-vii** [comment]
retest this please

**Comment by pfbuxton** [comment]
This issue is also present when one uses the alternative Python method for accessing data:
```python
conn = Connection(MDSplus_IP_address)
conn.openTree(tree,pulseNo)
time_inserted = conn.get("getnci("+place_to_read+",'TIME_INSERTED')").data()
```

Also when accessing data in Matlab.

In all three cases the overflow behaves differently, so a different number is generated.

Thanks,
Peter

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
