### PR TITLE
Fix: makeSegments bug in check_compress_dim

### PR DESCRIPTION
**Pull request by zack-vii**
Resolves TREE-E-INVDTPUSG error on MakeSegment due to bug in check_compress_dim.

### CODE REVIEW

**Review by joshStillerman — COMMENTED** [review]
Timo,
  Can you explain this change?  Where does initialvalue come from ?

**Comment by zack-vii** [comment]
sure: but i found that the method is called twice. need to go back to my desk.
this fixed writing but seems reading is now a problem
I will add some tests once i found the other issue

**Comment by zack-vii** [comment]
strange that it is now covered by our tests

**Comment by zack-vii** [comment]
well now its easier to explain.. begin_sinfo was calling checkcompress with 'mdsdsc_xd_t' but checkcompress expected 'mdsdsc_xd_t *'

**Comment by zack-vii** [comment]
writing and reading works now.

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
