### PR TITLE
Fix:handle the case of missing field for DeviceCoice and give better …

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
…explanation of error

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Review by AndreaRigoni — APPROVED** [review]
ok

**Pull request merged**
