### PR TITLE
Feature: Move pydevices to /usr/local/mdsplus/pydevices -Do not merge yet

### PR DESCRIPTION
**Pull request by tfredian**

### CODE REVIEW

**Review by zack-vii — COMMENTED** [review]
if the regular installation allows python to still import Devices according to the old importstring e.g.:
```python
from MitDevices import ACQ132
```
this should be fine. This was supported by the \_\_init\_\_.py files.

**Comment by tfredian** [comment]
It should still support devices implemented by installed modules but it is questionable why one would still package devices that way. The MitDevices, RfxDevices and W7xDevices will no longer be installed as site-packages and instead are moved to $MDSPLUS_DIR/pydevices/xxxDevices and referenced via the $MDS_PYDEVICE_PATH method.

**Review by zack-vii — DISMISSED** [review]
if people are aware of the changes this should not be to hard to adopt and therefor not break too much

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
