### PR TITLE
java maven

### PR DESCRIPTION
**Pull request by zack-vii**
addresses #1752

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
This PR looks scary but it only juggles with build files of java projects and javatraverser2. I simplified the Makefiles a lot by using wildcard instead of detailed lists. this is possibly also doable for jscope but it i got scarred by its complexity. maybe it is useful to put jtraverser and jscope in packages and add the appropriate folder structure. But i leave that to you or to later.

Once we have an account for jenkins set up we can deploy maven projects via
```sh
deploy/build.sh --os=maven --publish --keys=/mdsplus/certs
```
maybe as part of trigger.sh in the publish phase.

currently i published the parent pom, mdsplus-api, and jtraverser2 on maven-central
https://search.maven.org/search?q=g:org.mdsplus

I think mdsobjects or mdsclient could be candidates. but jscope and jtraverser would need some do-over.

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
Anyone, any opinion on this?

**Comment by joshStillerman** [comment]
I don't.  Don't know anything about maven. Seems fine to me. How big a 
change to the way we do java things would it be? Are there downsides?  
Effort/Complexity/Other ?

-Josh

**Comment by zack-vii** [comment]
well for in here I meant the relocation of projects in ./java/. this pr does what needed to be done for jtraverser2. we can add more projects later if we want. this pr does not change anything essential in other projects but simplifies the way they are built.

**Comment by joshStillerman** [comment]
Good by me.  I will let the java enthusiasts chime in if they want to.

**Comment by GabrieleManduchi** [comment]
I am in holidays now but in a copule pf days

**Comment by GabrieleManduchi** [comment]
I am on holidays now but in a couple of days i will look at it

**Comment by zack-vii** [comment]
retest thos please

**Pull request closed without merging**
