### PR TITLE
Zck fix cull and some cleanup

### PR DESCRIPTION
**Pull request by zack-vii**

### CODE REVIEW

**Comment by zack-vii** [comment]
```tdi
3..5 == 0 : 5
23..5 == 2 : 5
_a..5 == _ : 5
```
is a compiler issue. 
```tdi
3 .. 5 == 3 : 5
```
works!

**Comment by zack-vii** [comment]
fixes race from fc27 #'302 64-san-thread in MdsTdiTest.log

**Comment by zack-vii** [comment]
the fix for 1..3 compile is hacky but works. if anyone knows what cases it in the first place, please let me know.

I assume it has to do with the fact that both '..' (len=2) and ':' (len=1) map to the same operation

**Comment by zack-vii** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]
As per your EMAIL I am approving...

**Pull request merged**
