### PR TITLE
Fix: MAX_DIMS 8 for mdsip; make use of fill value

### PR DESCRIPTION
**Pull request by zack-vii**
addresses issue #1548

### CODE REVIEW

**Review by joshStillerman — COMMENTED** [review]
Can you write a test for this ?  local 8 dims ?  remote 8 dims ?  I would be surprised if anyone has every made an 8 dimensional object. 

I also wonder why remote was explicitly 7 dims

**Comment by zack-vii** [comment]
will do but looks like i have to do some more code replacements before it even matters
will try to grap zero([1,1,1,1,1,1,1,1],1) in MdsConnectionTest

**Comment by zack-vii** [comment]
7 wonders, 7 dwarfs, 7 dims .. maybe maybe not.

**Comment by zack-vii** [comment]
tested it with tditest and our old version server mds-data-2, looks like the server sets ndims to 8 if 8 is teh number of dims however it can only set 7 dims so the client can reconstruct the 8th dim from the message length if it is a multiple of the numbytes value upto the 7th dim. now you can even read 8dim array from old servers.

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
