### PR TITLE
Zck task timeout test and parallel tests using -j

### PR DESCRIPTION
**Pull request by zack-vii**
… and mdsip test for being executed in parallel

TODO: fix cpp tests that share tree files to be executed in parallel

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
after some try and error this achieves a decent speedup by parallelizing where it is possible. unfortunately jaspi froze in the process. I limited the number of cpu usage to hopefully prevent this from happening.

**Comment by zack-vii** [comment]
however fc25's valgrind test still takes almost 90 mins and should probably split into two jobs e.g. 64 and 32 bit

**Review by tfredian — DISMISSED** [review]

**Comment by zack-vii** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by tfredian — APPROVED** [review]

**Pull request merged**
