### PR TITLE
Fix: added missing finalize() to java MDSplus.Tree

### PR DESCRIPTION
**Pull request by zack-vii**

### CODE REVIEW

**Comment by zack-vii** [comment]
Hey @GabrieleManduchi, could you verify this against any interference with JTraverser or jScope. I think this should be the desired behavior (close tree of object gets destroyed)

**Comment by zack-vii** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
Thanks for anticipating me....

**Pull request merged**
