### PR TITLE
Fix:Top level devices in Java DecompileTree and Signal compile in mds…

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
…objects cpp

1) Devices at top level were not recognized as devices. Not they are
2) The Signal descriptor now requires that length field be 0. Solved by adding a Signal specific convertToDsc() method overriding that of Compound

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by tfredian — APPROVED** [review]

**Pull request merged**
