### PR TITLE
Zck python; refactor ScopeUtilities

### PR DESCRIPTION
**Pull request by zack-vii**
might still have memory issues

### CODE REVIEW

**Comment by zack-vii** [comment]
this might be it

**Review by tfredian — APPROVED** [review]
I don't know much about jScope related features so can't really tell if this will break anything. I'll assume it is ok and approved it but perhaps Gabriele should probably review this soon before merging it.

**Comment by zack-vii** [comment]
please review followup #1634 instead

**Comment by GabrieleManduchi** [comment]
The changes to ScopeUtilities seem reasonable, but it is hard for me to verify in the code due to the large number of modifications.
Let's cross fingers. I will make some more extensive tests in order to make sure that nothing got broken.

**Comment by zack-vii** [comment]
cool thanks. if there is anything different now it should be easier to adapt though.

**Pull request merged**
