### PR TITLE
Fix:removed __init__.py no more required, that breaks MARTE2 python d…

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
…evices

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Review by zack-vii — CHANGES_REQUESTED** [review]
This ahould be 3 prs
1.) the fix for jtraverser
2.) the removal of \_\_init\_\_.py
3.) adding a device

**Review by zack-vii — CHANGES_REQUESTED** [review]
if you remove \_\_init\_\_.py this will break compatibility witj=h old import method.
we cannot do this. move marte into pydevices MARTE instead and we should really discuss to freeze the content of Mit/RfxDevices and co. and stop making it worse.

#1977

**Comment by GabrieleManduchi** [comment]
For the moment I revert __init__.py . In a later PR I will move MARTe2 devices into a separate RfxDevices directory

**Comment by zack-vii** [comment]
would be solved by #1977

**Comment by zack-vii** [comment]
device integration included in #1977 (e560e81)

**Pull request closed without merging**
