### PR TITLE
Fix:protect cpp mdsevent AST with a mutex to avoid race conditions

### PR DESCRIPTION
**Pull request by GabrieleManduchi**

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
Protect AST used in MDSEvent object with a mutex to avoid race conditions

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
Josh, now tests are passed, could you accept my PR?

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
