### PR TITLE
Gm marte2 sample

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Update MARTe2 MDSplus framework + devices for Demo

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please again

**Comment by zack-vii** [comment]
rebase this please

**Comment by zack-vii** [comment]
reason for the tests to fail was an issue with docker on one of the workers

**Comment by joshStillerman** [comment]
I was looking at the workers trying to disable the ones that were 
broken.  But then had a meeting.  I guess it knows to ignore the ones 
that are down, but (obviously) not the ones that are broken

Thanks

-Josh

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
