### PR TITLE
New D-TACQ devices for streaming and transient captures.

### PR DESCRIPTION
**Pull request by seanalsop**
Both acq1001 and acq2106 are included.
Also included is a new copy of acq400_hapi, which (some of) the code in the devices relies on.

### CODE REVIEW

**Comment by joshStillerman** [comment]
ok to test

**Comment by zack-vii** [comment]
rebase this please

**Comment by zack-vii** [comment]
also unfortunatly teh branch name can only have 12 chars

**Comment by zack-vii** [comment]
and if you are at it. it would be great if the devices would work with both python2 and 3
e.g.:
```python
if sys.version_info<(3,):
    import Queue as queue
else:
    import queue
```

**Comment by zack-vii** [comment]
PR :  #1976 has these issues addressed and replaces this PR

**Pull request closed without merging**
