### PR TITLE
Gm fix cpp ctx

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Handle the new limitation about tree context in multithreaded applications in order to let Tree and TreeNode instances be exchanged among different threads. The Tree contexts are now contained in a Tree private array indexed by thread id. When the Tree instance is used in a new thread, the tree is open again and the new context recorded in the array

Changed C++and Java versions + corresponding tests

### CODE REVIEW

**Comment by zack-vii** [comment]
on fc32
looks like a java test fails.. with a critical exception core dump

16:50:27 /git/mdsplus/conf/test-driver: line 120: 21647 Aborted                 (core dumped) "$@" > $log_file 2>&1
16:50:27 FAIL: MDSplus.MdsTreeTest

**Comment by zack-vii** [comment]
http://jenkins2.mdsplus.org/job/fc32/ws/tests/64/java/mdsobjects/tests/MDSplus.MdsTreeTest.log/*view*/

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by zack-vii** [comment]
since the issue in jenkins memcheck seems to be a some unrelated python cleanup thing. you may review the code and merge it.
 I would suggest you use the ./clang-format before checking it in though.

**Comment by zack-vii** [comment]
unfortunately, i currently dont have more time to review it further than that

**Review by AndreaRigoni — APPROVED** [review]
Ok ... nice !

**Pull request merged**
