### PR TITLE
Fix memory misaglinment in labview interface for 32 bits

### PR DESCRIPTION
**Pull request by GabrieleManduchi**

### CODE REVIEW

**Review by tfredian — CHANGES_REQUESTED** [review]
Enclose #pragma pack(1) in
 #ifndef **MINGW64**
#pragma pack(1)
#endif

**Comment by GabrieleManduchi** [comment]
Surreounded #pragma pack(1) directive in #ifndef **MIGNW64**  (with underscores)

**Comment by GabrieleManduchi** [comment]
"**MINGW64**"

**Comment by drjdpowell** [comment]
Hello, I’m trying to use the objects LabVIEW library for Mdsplus on a 32-but system.  The library works, but any misuse or error seems to crash LabVIEW.   Could the crashes be a result of this issue?

**Pull request merged**
