### PR TITLE
Fix: Repair tree context handling in MDSplus python

### LINKED ISSUE #1064: Improper handling of tree ctx in MDSplus python modules
When performing calls into TreeShr and TdiShr the tree ctx information often is not saved within the data objects returned. This results in the use of the wrong tree ctx when later accessing information in the data objects. A good example of this problem is found by running the following code:

import MDSplus as M
M.setenv("ctxbug1_path","/tmp")
M.setenv("ctxbug2_path","/tmp")
t=M.Tree("ctxbug1",-1,"new")
s=t.addNode("bug1_sig","signal") 
d=t.addNode("bug1_dim","axis")
l=t.addNode("bug1_list","any")
d.record=42
s.record=M.Signal(1,None,d)
l.record=[s,d]
t.write()
t=M.Tree("ctxbug2",-1,"new")
s=t.addNode("bug2_sig","signal")
d=t.addNode("bug2_dim","axis")
d.record=142
s.record=M.Signal(100,None,d)
t.write()
t=M.Tree("ctxbug1",-1)
print("decompile bug1_sig")
M.tcl('decompile bug1_sig')
print("decompile bug1_dim")
M.tcl('decompile bug1_dim')
print("decompile bug1_list")
M.tcl('decompile bug1_list')
t2=M.Tree("ctxbug2",-1)
print("decompile bug2_sig")
M.tcl('decompile bug2_sig')
print("decompile bug2_dim")
M.tcl('decompile bug2_dim')
print("BUG1_SIG.record=%s"%str(t.BUG1_SIG.record))
print("BUG1_SIG.record.data()=%s"%str(t.BUG1_SIG.record.data()))
print("All looks good... Now for the bad stuff")
print("BUG1_SIG.record.dim_of(0).data()=%s"%str(t.BUG1_SIG.record.dim_of(0).data()))
print("BUG1_SIG.record.dim_of(0)=%s"%str(t.BUG1_SIG.record.dim_of(0)))
print("BUG1_LIST.record=%s"%str(t.BUG1_LIST.record))

This now (as of mdsplus-alpha 7.18.3) produces:

decompile bug1_sig
Build_Signal(1, *, BUG1_DIM)
decompile bug1_dim
42
decompile bug1_list
[BUG1_SIG,BUG1_DIM]
decompile bug2_sig
Build_Signal(100, *, BUG2_DIM)
decompile bug2_dim
142
BUG1_SIG.record=Build_Signal(1, *, BUG1_DIM)
BUG1_SIG.record.data()=1
All looks good... Now for the bad stuff
BUG1_SIG.record.dim_of(0).data()=142
BUG1_SIG.record.dim_of(0)=\CTXBUG2::TOP:BUG2_DIM
BUG1_LIST.record=[BUG2_SIG,BUG2_DIM]

The problem is likely not limited to these examples but might be more pervasive throughout. This problem is particularly bad when two or more trees of the same nids are open since it may not be noticed. If different tree types are open you may get invalid tree or no such node errors as the node ids may not exist in the different trees.

### PR DESCRIPTION
**Pull request by tfredian**
This is to fix https://github.com/MDSplus/mdsplus/issues/1064

### CODE REVIEW

**Comment by joshStillerman** [comment]
I will leave this to Timo to look at.

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please    again intermittent failures with MdsConnectionTest

**Comment by tfredian** [comment]
retest this please failures might be caused by problem with a jenkins slave.

**Review by joshStillerman — APPROVED** [review]
Can not really assess this.  But lets try it.

**Pull request merged**
