### PR TITLE
Minor fixes here and there

### PR DESCRIPTION
**Pull request by bstandley**
- In device_support/camera_utils I changed the Makefile and added unistd.h to camstreamutils.cpp to make it compile out-of-the-box on my machine.
- I increased the number of columns in traverser's Add Device dialog because the last few rows were getting cut off on my 1080p monitor.
- The rest are single-char typos.

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
Hi Brian,
    thanks!
       Gabriele

On 29/05/2015 21:59, Brian Standley wrote:

> - In device_support/camera_utils I changed the Makefile and added
>   unistd.h to camstreamutils.cpp to make it compile out-of-the-box
>   on my machine.
> - I increased the number of columns in traverser's Add Device dialog
>   because the last few rows were getting cut off on my 1080p monitor.
> - The rest are single-char typos.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/MDSplus/mdsplus/pull/5
> 
> ```
>     Commit Summary
> ```
> - Minor fixes here and there
>   
>   ```
>   File Changes
>   ```
> - _M_ device_support/camera_utils/Makefile
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-0 (6)
> - _M_ device_support/camera_utils/camstreamutils.cpp
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-1 (1)
> - _M_ javadevices/CYGNET4KSetup.form
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-2 (2)
> - _M_ javadevices/CYGNET4KSetup.java
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-3 (2)
> - _M_ traverser/traverser.uil
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-4 (2)
> - _M_ xml/tcl_commands.xml
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-5 (2)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/MDSplus/mdsplus/pull/5.patch
> - https://github.com/MDSplus/mdsplus/pull/5.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/5.

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by GabrieleManduchi** [comment]
Hi Brian,
    do you have permission on alpha branch? If yes, go ahead and commit 
the changes.

```
                                         Gabriele
```

On 29/05/2015 21:59, Brian Standley wrote:

> - In device_support/camera_utils I changed the Makefile and added
>   unistd.h to camstreamutils.cpp to make it compile out-of-the-box
>   on my machine.
> - I increased the number of columns in traverser's Add Device dialog
>   because the last few rows were getting cut off on my 1080p monitor.
> - The rest are single-char typos.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/MDSplus/mdsplus/pull/5
> 
> ```
>     Commit Summary
> ```
> - Minor fixes here and there
>   
>   ```
>   File Changes
>   ```
> - _M_ device_support/camera_utils/Makefile
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-0 (6)
> - _M_ device_support/camera_utils/camstreamutils.cpp
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-1 (1)
> - _M_ javadevices/CYGNET4KSetup.form
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-2 (2)
> - _M_ javadevices/CYGNET4KSetup.java
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-3 (2)
> - _M_ traverser/traverser.uil
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-4 (2)
> - _M_ xml/tcl_commands.xml
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-5 (2)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/MDSplus/mdsplus/pull/5.patch
> - https://github.com/MDSplus/mdsplus/pull/5.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/5.

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by GabrieleManduchi** [comment]
Minor fixes/typo corrections

**Comment by GabrieleManduchi** [comment]
Hi Brian,
    I think I did it from github.

```
             Gabriele
```

On 29/05/2015 21:59, Brian Standley wrote:

> - In device_support/camera_utils I changed the Makefile and added
>   unistd.h to camstreamutils.cpp to make it compile out-of-the-box
>   on my machine.
> - I increased the number of columns in traverser's Add Device dialog
>   because the last few rows were getting cut off on my 1080p monitor.
> - The rest are single-char typos.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/MDSplus/mdsplus/pull/5
> 
> ```
>     Commit Summary
> ```
> - Minor fixes here and there
>   
>   ```
>   File Changes
>   ```
> - _M_ device_support/camera_utils/Makefile
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-0 (6)
> - _M_ device_support/camera_utils/camstreamutils.cpp
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-1 (1)
> - _M_ javadevices/CYGNET4KSetup.form
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-2 (2)
> - _M_ javadevices/CYGNET4KSetup.java
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-3 (2)
> - _M_ traverser/traverser.uil
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-4 (2)
> - _M_ xml/tcl_commands.xml
>   https://github.com/MDSplus/mdsplus/pull/5/files#diff-5 (2)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/MDSplus/mdsplus/pull/5.patch
> - https://github.com/MDSplus/mdsplus/pull/5.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/5.

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by bstandley** [comment]
Hi Gabriele,
Thanks for doing the merge.  I do not have write access but it _would_ be nice to have . . .
-Brian

**Pull request merged**
