### PR TITLE
Fix: nullpointer access in ScopeUtilities if no limits specified

### PR DESCRIPTION
**Pull request by zack-vii**

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
Not sure that the use of int16_t in ScopeUtilities (line 662 old, 631 new)  is correct........

**Comment by zack-vii** [comment]
good find, fixed it

**Comment by GabrieleManduchi** [comment]
Another thing: lines

 *(int *)&retArr[idx] = yLabel->length;	 
    swap4(&retArr[idx]);	

are replaced by 
   SWAP32(&retArr[idx],&yLabel->length);

but  it seems to me that  yLabel->length is a short, and in the replacement it is considered as long

**Comment by zack-vii** [comment]
This is just like in the original code. Since length is unsigned but java can only handle signed length is written out as int. Thus the full int has to be swapped for java is bigendian

**Comment by GabrieleManduchi** [comment]
ylabel->length is a short. I agree that we possibly need swapping but instruction  SWAP32(&retArr[idx],&yLabel->length); copies (possibly swapped) bytes that do not belong to yLabel->length (2 bytes).

Am I missing anything?

**Comment by GabrieleManduchi** [comment]
Seems ok now, but just one last question: why do you mask length field (short) with 0xffff?

**Comment by zack-vii** [comment]
to make sure its unsigned. its also doing the cast to int. i am not sure if this is necessary but it is a more obvious variant of casting to int that tells you: 'this is an unsigned short'.

**Review by GabrieleManduchi — APPROVED** [review]

**Pull request merged**
