### PR TITLE
Git release

### PR DESCRIPTION
**Pull request by AndreaRigoni**
Fix: removed reference to RELEASE_COMMIT and RELEASE_BRANCH

Now available as GIT_COMMIT and GIT_BRANCH
If a RELEASE_VERSION has not been set by trigger.sh the RELEASE_TAG will be
equal to GIT_TAG. And the GIT_TAG has the unique commit hash inside.

### CODE REVIEW

**Comment by AndreaRigoni** [comment]
Retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by AndreaRigoni** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by tfredian — APPROVED** [review]

**Review by tfredian — CHANGES_REQUESTED** [review]
It seems this PR needs to be rebased and there are some conflicts which cannot be rebased automatically.

Unrelated info....

The problems with the PR testing was due to a docker update on the Ubuntu machines which required the docker service to be restarted manually. After I restarted docker on the mfews's the PR build completed successfully. I am looking into adding a feature of the pr trigger job to restart docker on the mfews's before starting the builds as this has happened several times in the past. I have only seen this problem on Ubuntu.

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by AndreaRigoni** [comment]
Tom, could you give me a hint on how to test the conflict? I don't see it .. but I'm not actually rebasing the all branch, because I merged alpha on this branch at a certain point to update the commits from alpha.. there seems to be any conflict in this way.. do I have to rebase the entire branch? If so I may have to start over and apply all these commits picking cherries from here into alpha :-)

**Review by tfredian — APPROVED** [review]

**Comment by tfredian** [comment]
Hmmm, if you look at this pr page on github it says there is a conflict preventing rebasing. To the right of the Remase and Merge" section there is a "view command line instructions" link which shows:

Step 1: From your project repository, check out a new branch and test the changes.
```
git checkout -b AndreaRigoni-git_release alpha
git pull https://github.com/AndreaRigoni/mdsplus.git git_release
```
Step 2: Merge the changes and update on GitHub.
```
git checkout alpha
git merge --no-ff AndreaRigoni-git_release
git push origin alpha
```
So I tried the following instead:
```
git checkout alpha
git pull
git checkout -b AndreaRigoni-git_release alpha
git pull https://github.com/AndreaRigoni/mdsplus.git git_release
git rebase alpha
```
This produced complaints about conflicts so I then did git status and got:
```
[twf@cmodws103 mdsplus-alpha]$ git status
rebase in progress; onto 82ae6ff
You are currently rebasing branch 'AndreaRigoni-git_release' on '82ae6ff'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   Makefile.inc.in
        both modified:   configure.ac
        both added:      m4/ax_git_revision.m4

```
I'm not sure but I suspect if you replace those three files with the contents of your PR branch files, do the git add of each, and then git rebase --continue you'll end up with the new branch rebase on current alpha and then push that new branch to your project and do another PR.
Hope this helps....

**Comment by AndreaRigoni** [comment]
moved to #1701 to rebase alpha instead of merge commits.

**Pull request closed without merging**
