### PR TITLE
Fix: tools assisted tests for alpha - and fixes

### PR DESCRIPTION
**Pull request by zack-vii**
This will likely fail because the supressions need to be updated. well .. not because jenkins does not trigger the jobs yet

### CODE REVIEW

**Comment by zack-vii** [comment]
* covered rhel8 issue with 32bit tests.. redhat can now use arch to restrict tests.
* reset all suppressions and started to build suppressions for most modern os: fc32
* added os jobs for all tool tests
* enabled sanitiser for java tests - may fail miserably but with luck it will only requires some java suppressions
* fixed java configuration

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]
Timo -
  This looks great !  Untangling how builds / releases / tests are done!

**Pull request merged**
