### PR TITLE
Zck accumulate

### PR DESCRIPTION
**Pull request by zack-vii**
fixes some issues with tdi functions and octaword. uses more int63_t instead quadword

### CODE REVIEW

**Comment by zack-vii** [comment]
tests almost all builtin functions listed in
http://www.mdsplus.org/index.php/Documentation:Reference:TDI_INDEX

lowercase function seem to be fortran only
fixes bugs found along the way

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Review by tfredian — APPROVED** [review]
looks ok as far as I can tell. Fixing tdishr is inherently difficult.

**Pull request merged**
