### PR TITLE
Gm fix jscope img

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Fix byte pixels so that all 8 bits (unsigned) are correclty used in java

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Review by AndreaRigoni — APPROVED** [review]
Ok but this adds commits also for redpitaya, it could be misleading to squash and merge... Maybe we should only merge this without squash?

**Pull request merged**
