### PR TITLE
Fix conversion of floating values using TEXT

### LINKED ISSUE #2823: Conversion of floating point values using TEXT is using the VMS syntax on Linux machines.
**Affiliation**
SPC-EPFL

**Version(s) Affected**
Server Version: Stable 7.142.81

**Platform(s)**
Ubuntu 22.04

**Installation Method(s)**
DEB package installed from MDSplus repository

**Describe the bug**
Text conversion of floating point values using `TEXT` is using the VMS syntax on Linux machines.
`TEXT(1.0)` or `TEXT(FS_FLOAT(1.0))` yield `"       1.00000S0"` while `"       1.00000E0"` was expected (and was the case prior to stable version 7.79.0).

**To Reproduce**
1. Open `tdic`
2. type `TEXT(1.0)`
3. Output if `"       1.00000S0"`

**Expected behavior**
The answer should be `"       1.00000E0"`. The main issue is that "1.00000S0" cannot be converted to a floating point number in other codes/languages.

**Screenshots**
```
$ tdic
TDI> TEXT(1.0)
"       1.00000S0"
```

### PR DESCRIPTION
**Pull request by merlea**
Fixes #2823.

The cause of the issue is that ever since 0d95b94c (which first appeared in the `stable_release-7-79-0`) `DTYPE_*` are not CPP macros anymore but enumerated types. Hence the CPP directive `#if DTYPE_F == DTYPE_NATIVE_FLOAT` was always true and the VMS settings were enforced.

Looking at `mdsdescrip.h` it seems that now the VMS build is not supported anymore and `DTYPE_NATIVE_FLOAT` is always defined to be `DTYPE_FS`, so I just removed the VMS option from `TdiConvert.c` as a fix.

### CODE REVIEW

**Comment by mwinkel-dev** [comment]
Retest this please.

**Comment by mwinkel-dev** [comment]
Preceding "retest" post is a request to Jenkins, not a request to merlea.

**Comment by merlea** [comment]
Hi @mwinkel-dev, thanks I have submitted a few PRs to MDSplus now so am used to this.

By the way, let me know if you think some tests should also be added for this fix. I might need some guidance on how to implement them though. (Same for #2821 ).

**Review by joshStillerman — APPROVED** [review]

**Comment by joshStillerman** [comment]
A test for this would be great.  I have approved it regardless.  Thanks.

**Pull request merged**
