### PR TITLE
Fix: UdpEventGetInterface for Windows

### PR DESCRIPTION
**Pull request by zack-vii**
added some debug options and ported the UdpEventGetInterface method to Windows

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
no sure why alpine randomly segfaults in MdsTdiTest
i downloaded the full workspace and unpacked everything locally into the respective folder ./build/<os>
i could open the core and it told me there was a segfault here ?
```gdb
(gdb) list
114           results[thread_idx]=thread_idx;
115           if (pthread_create(&threads[thread_idx], attrp, ThreadTest, &results[thread_idx]))
116             break;
117         }
118         if (attrp) pthread_attr_destroy(attrp);
119         if (thread_idx<NUM_THREADS) fprintf(stderr,"Could not create all %d threads\n", NUM_THREADS);
120         for (thread_idx = 0 ; thread_idx<NUM_THREADS ; thread_idx++)
121           pthread_join(threads[thread_idx],NULL);
122         for (thread_idx = 0 ; thread_idx<NUM_THREADS ; thread_idx++)
123           TEST0(results[thread_idx]);
(gdb)
```
not sure which line it now is.
I if i run the very code it has no problems. If someone could manually run the test a number of times on the jenkins worker in the respective docker image. i am sure the issue lies withing the docker and the host.

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
I dedicated a new label alpine to the alpine-x86 builds on cmod103 in hope this will take out some of the randomness.

**Comment by zack-vii** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by tfredian — APPROVED** [review]

**Pull request merged**
