### PR TITLE
Dev gm

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Fix some middes updates for signals with absolute times

### CODE REVIEW

**Comment by zack-vii** [comment]
This merge is a mess due to the changes in 27db66a. Is there a chance to clean up this merge to its essential changes

**Comment by GabrieleManduchi** [comment]
Hi
     ??????

```
     I did not make any push directly.....only a pull request 
```

yesterday with only the right files changed.......    what is happening???

```
                                         Gabriele
```

On 31/03/2016 13:05, zack-vii wrote:

> This merge is a mess due to the changes in 27db66a 
> https://github.com/MDSplus/mdsplus/commit/27db66ace6b8c10cb9e0fc4fbc966392b928de06. 
> Is there a chance to clean up this merge to its essential changes
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/428#issuecomment-203879323

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by zack-vii** [comment]
also it should replace "\" with "\\" i.e. ->\
recommend to revert this merge and redo a clean one

**Comment by zack-vii** [comment]
The changes in MdsDataProvider.java simplify to:

``` java
        public SimpleWaveData(String in_y, String experiment, long shot)
        {
            this(in_y,null,experiment,shot);
        }

        public SimpleWaveData(String in_y, String in_x, String experiment, long shot)
        {
            this.wd_experiment = experiment;
            this.wd_shot = shot;
            if(checkForAsynchRequest(in_y))
            {
                this.in_y = "[]";
                this.in_x = "[]";
             }
            else
            {
                this.in_y = in_y;
                this.in_x = in_x;
            }
            v_idx = var_idx;
            var_idx += 2;
            if(segmentMode == SEGMENTED_UNKNOWN)
            {
                Vector args = new Vector();
                String fixedY = in_y.replaceAll("\\\\", "\\\\\\\\");
                args.addElement(new Descriptor(null, fixedY));
                try {
                    byte[] retData = GetByteArray("byte(MdsMisc->IsSegmented($))", args);                              
                    if(retData[0] > 0)
                        segmentMode = SEGMENTED_YES;
                    else
                        segmentMode = SEGMENTED_NO;

                }catch(Exception exc)
                {
                    error = null;
                    segmentMode = SEGMENTED_UNKNOWN;
                }
            }
        }
```

**Comment by GabrieleManduchi** [comment]
I confess  my ignorance.....I changed only a couple of lines in those 
files, and followed the usual procedure I really don't know why git 
reports such a huge change.

Tom, any advise?

```
         Gabriele
```

On 31/03/2016 14:30, zack-vii wrote:

> also it should replace "\" with "\" i.e. ->\
> recommend to revert this merge and redo a clean one
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/428#issuecomment-203908562

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by GabrieleManduchi** [comment]
Tom may revert the change but I fear that the next pull request will 
present the same issue, despite the fact that only few lines have been 
changed.

On 31/03/2016 14:35, zack-vii wrote:

> The changes in MdsDataProvider.java simplify to:
> 
> ```
>      public  SimpleWaveData(String  in_y,String  experiment,long  shot)
>      {
>          this(in_y,null,experiment,shot);
>      }
> 
>      public  SimpleWaveData(String  in_y,String  in_x,String  experiment,long  shot)
>      {
>          this.wd_experiment=  experiment;
>          this.wd_shot=  shot;
>          if(checkForAsynchRequest(in_y))
>          {
>              this.in_y=  "[]";
>              this.in_x=  "[]";
>           }
>          else
>          {
>              this.in_y=  in_y;
>              this.in_x=  in_x;
>          }
>          v_idx=  var_idx;
>          var_idx+=  2;
>          if(segmentMode==  SEGMENTED_UNKNOWN)
>          {
>              Vector  args=  new  Vector();
>              String  fixedY=  in_y;
>              fixedY.replaceAll("\\","\\\\");
>              args.addElement(new  Descriptor(null, fixedY));
>              try  {
>                  byte[] retData=  GetByteArray("byte(MdsMisc->IsSegmented($))", args);
>                  if(retData[0]>  0)
>                      segmentMode=  SEGMENTED_YES;
>                  else
>                      segmentMode=  SEGMENTED_NO;
> 
>              }catch(Exception  exc)
>              {
>                  error=  null;
>                  segmentMode=  SEGMENTED_UNKNOWN;
>              }
>          }
>      }
> ```
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/428#issuecomment-203911078

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by zack-vii** [comment]
that's alright. GitHub does this sometimes e.g when updating the pull request to the latest head. I usually check the final changelog before I merge and force push a clean rebased version of the committed branch in case the current merge got messed up.

**Comment by GabrieleManduchi** [comment]
Ok, I let Tom do it then I will make again a pull request.

On 31/03/2016 14:52, zack-vii wrote:

> that's alright. GitHub does this sometimes e.g when updating the pull 
> request to the latest head. I usually check the final changelog before 
> I merge and force push a clean rebased version of the committed branch 
> in case the current merge got messed up.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/428#issuecomment-203920178

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by zack-vii** [comment]
I that case your branch probably needs to be rebased to the latest head (after it has been cleaned up) or you should clean it up manually using

```
git rebase -i <sha-hash>
```

**Comment by zack-vii** [comment]
update.. the replaceAll does not work since it is not an in-place operation. in the current implementation it has not effect whatsoever. is it really required. if so i updated the sample code from earlier.

**Pull request merged**
