### PR TITLE
Kge config cleanup

### PR DESCRIPTION
**Pull request by kgerickson**
Moderate cleanup of some old configure issues:
- Remove support for old platforms and tools
- Update automake
- General cleanup

### CODE REVIEW

**Comment by tfredian** [comment]
CamShr cannot build on windows (not sure about macosx) so the test for the scsi/sg.h header is still needed. Eventually I would like to change camshr to build on windows to provide the remote camac functionality and generate errors if "camac_server" env is not set and get rid of remcamshr entirely.

**Comment by kgerickson** [comment]
I modified the branch to remove that commit.  Do I have to resend a new pull request?

**Comment by kgerickson** [comment]
Ok, I just opened a new one

**Comment by tfredian** [comment]
Actually if this is the one I closed then you could have reopened it 
after pushing changes.

**Pull request closed without merging**
