### PR TITLE
python rfxdevices update

### PR DESCRIPTION
**Pull request by zack-vii**
- updated RfxDevices and checked them at least up to adding them to a tree.
- thereby I found and fixed some errors
- using Device.debug to toggle output
- speedup of the import procedure by simplifying the parts creation and avoiding computation

### CODE REVIEW

**Comment by zack-vii** [comment]
I did not choose selective errors for each case but replaced the return 0 with Essential error instead. could be enhanced by choosing the right ones. The generic error base would come in handy.
such as file not found, parameter invalid, parameter out of range, device no initialized, ...
I tested the devices using a python script that adds all of them to a test tree

``` python
from os import environ
environ['DEBUG_DEVICES'] = '1'
import RfxDevices as D, MDSplus as M
with M.Tree('test',-1,'new') as t:
    done = False
    for name in sorted(D.__dict__.keys()):
        cls = D.__dict__[name]
        if isinstance(cls, type) and issubclass(cls, M.Device):
            print(name)
            pathparts = name.split('_')
            node = t.top
            if len(name)>9 and len(pathparts)>1:
                name = '_'.join(pathparts[1:])
                try:
                    node = node.getNode(pathparts[0]+'_')
                except:
                    node = node.addNode(pathparts[0]+'_','STRUCTURE')
                    t.write()
            cls.Add(node,name)
            t.write()
```

requires #250

**Comment by zack-vii** [comment]
may it helps if I rebase it

**Comment by GabrieleManduchi** [comment]
The problem however seems to be related to the certificate used.

On 10/12/2015 12:30, zack-vii wrote:

> may it helps if I rebase it
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/pull/251#issuecomment-163584482.

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by GabrieleManduchi** [comment]
Ok, this time it worked

**Pull request merged**
