### PR TITLE
Fix: add timeout and return not triggered on timeout

### PR DESCRIPTION
**Pull request by santorofer**
The device acq435st has been modified to deal with trigger timeout (including error handling): it will return Not Trigged on timeout.

### CODE REVIEW

**Review by joshStillerman — COMMENTED** [review]
please return 1
try to trim lines to ~ 80 chars

**Review by joshStillerman — COMMENTED** [review]
Why did every line change ?

**Review by joshStillerman — APPROVED** [review]
Note that for devices that are not brand new - the ones we don't know all of the users of 
we do not add nodes / change the tree structure.  
this is because, if people have models with these devices in them changing the node list will break their models.

In this case it is fine, since we know exactly who is using this device

**Comment by zack-vii** [comment]
FYI: python device methods should  not return any status code .. please return nothing on success and raise an mdsplus exception on error.
returning an int is interpreted as status value only for backward compatibility and deprecated.

**Comment by joshStillerman** [comment]
OK -

   Fernando will change it back.

-Josh

**Pull request merged**
