### PR TITLE
Gm marte2 streaming

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
MARTe2 devices updated to the latest version used in the meeting demo

### CODE REVIEW

**Comment by zack-vii** [comment]
could you rebase this branch please

**Review by zack-vii — CHANGES_REQUESTED** [review]
Could you revert the chmod of DEMOADC.py to 644?

**Review by zack-vii — CHANGES_REQUESTED** [review]
chmod for tdi/java/checkMarte.py should be 644

**Comment by GabrieleManduchi** [comment]
ported protections to 644

**Review by zack-vii — DISMISSED** [review]

**Comment by zack-vii** [comment]
I rebased it (hard) turns out its just adding a few devices so its safe. @GabrieleManduchi please reset your local branch to this one or better to alpha once the pr is merged.

**Review by zack-vii — APPROVED** [review]
rebased and nice.. if the devices work can only be judged by the author

**Comment by zack-vii** [comment]
retest this please

**Pull request merged**
