### PR TITLE
Fix: device setup

### LINKED ISSUE #2091: Device setup issues
When trying to bring up the form for a DIO2 module I find:
jTraverser 
   - chokes with internal java error and core dumps
jTraverser2 
  - sometimes works fine, and sometimes only displays 'reset' and 'Cancel' buttons.
  - always prints out a ton of messages about not being able to read from empty nodes.
traverser
  - complains: 
```
Error: /usr/local/mdsplus/lib/libJavaMds.so: undefined symbol: deviceSetup
```

MDSplus version:
```
jas@tokzonemit:~$ mdstcl
TCL> sho version


MDSplus version: 7.109.6
----------------------
  Release:  alpha_release_7.109.6
  Browse:   https://github.com/MDSplus/mdsplus/tree/alpha_release_7.109.6
  Download: https://github.com/MDSplus/mdsplus/archive/alpha_release_7.109.6.tar.gz


TCL> 
```

### PR DESCRIPTION
**Pull request by zack-vii**
to call it from within MDSPLUS_DIR/java/classes
```sh
java -cp "jTraverser2.jar;Devicebeans.jar;jDevices.jar;jScope.jar" mds.devices.Device expt shot path
```

### CODE REVIEW

**Comment by santorofer** [comment]
Timo, I was trying to test it, to see what I get if I run your java command. So I cloned your repo and checkout your  "zck-device-setup".

When I build it, using "bootstrap" and then configure, I'm not getting in the end the directory structure that you are expecting. 

For example, I don't have "java/classes", and also I don't see "java/jtraverser2/src/main/java/mds/devices/Device.java". What I get is "java/jtraverser2/classes/mds/devices"

Am I building it wrong?

**Comment by zack-vii** [comment]
hm well i nad is a short version but in the end in an installed fs there should be a java/classes folder in $MDSPLUS_DIR where you find all .jar files.
Device.java is here
https://github.com/MDSplus/mdsplus/blob/alpha/java/jtraverser2/src/main/java/mds/devices/Device.java
which will be compiled and packed into jtraverser2.jar. tge other jars are requred to open the setup,

as an easy way use the jtraverser2 bin script and replave the entrypoint with mds.devices.Device . that should do it.

**Comment by zack-vii** [comment]
i added the executable scripts setupDevice.template/bat in java/jtraverser2
e.g. \TEST::TOP:DEVICE is DIO2 device
```sh
setupDevice test -1 DEVICE
```

**Comment by zack-vii** [comment]
retest this please

failed because /mdsplus was not mounted on all slaves

**Comment by zack-vii** [comment]
TODO: tdi calls should use something like:
```tdi
execute("spawn('setupDevice $ $ $')", $EXPT, $SHOT, getnci(_nid, "FULLPATH"))
```
python could use os.system() or subprocess.POpen or similar

edit: on that note if the tdi functions are converted to python scripts they could use a shared python method to do the system call

**Comment by santorofer** [comment]
Hi Timo,
Just tested your setupDevice executable with one of our test trees that had a DIO2.
It worked well, it seems.
Cheers!

**Comment by zack-vii** [comment]
great thanks for testing. how do we go from here. i can implement the puthon api. should it be a separate pr? or should we merge this first

**Review by GabrieleManduchi — APPROVED** [review]

**Pull request merged**
