### PR TITLE
Zck tditest

### LINKED ISSUE #1583: tditest broken in recent releases
Several shell scripts using tditest are in use in cron jobs which do something like:
```
#!/bin/sh
tditest <<EOF > /dev/null
<tdi-commands>
EOF
```
These now result in segfaults. The tdi commands do get executed but there is a segfault when the EOF is reached. A simple test which could be added to the test suite which exhibits the behavior is:

```
#!/bin/sh
tditest <<EOF
42
EOF
```

### PR DESCRIPTION
**Pull request by zack-vii**
should fix  #1583

### CODE REVIEW

**Comment by tfredian** [comment]
retest this please

**Comment by zack-vii** [comment]
someone please approve

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by zack-vii** [comment]
included in #1588

**Pull request closed without merging**
