### PR TITLE
Feature: jTraverser and DeviceBeans

### LINKED ISSUE #1958: jTraverser2 meets device beans
Requirements:
- devicebeans must be elevated to package devices, i.e. moved to java/jdevices/src/main/java/devices
- either devicebeans should wrap around mdsplus-api or need to get their API calls adapted

### PR DESCRIPTION
**Pull request by zack-vii**
This is for sharing progress with @GabrieleManduchi 

TODO: 
- build jar and add to jTraverser2 startup scripts
- fix jTraverser.bat for windows
- add pydevice pkg
- update the javatraverser?.bat (issue #2021)
- maybe remove the .mak files

@GabrieleManduchi 
TEST new editors on dtacq example
- add pydevices from repo tp MDS_PYDEVICE_PATH
- start jTraverser2
- open new tree
- add ACQ2106_ACQ480x6
- check out Setup Device

TEST devicebeans support
- complie java/jdevices/src/jtraverser2/java into $OUTDIR
- $OUTDIR,jTraverser2.jar;jScope.jar;jDevices.jar to classpath and start jTraverser2
- open new tree
- add device
- check out Setup Device

waves and others seem to work except the ones mentioned in #1958

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
I followed your instructions, installed your branch and added jDevices to classpath, but I cannot set-up devices included in jDevices. I did not understand whether the device bean classes have been already moved to jDevices. If not I can do it.

**Comment by zack-vii** [comment]
they have not. they would have to be piacked with jtraverser2 or they woild conflict with jtraverser. you need to manually compile them and add them to classpath for testing. they require jtraverser2.jar and jscope.jar

**Comment by GabrieleManduchi** [comment]
It is not a big work to move the java beans stuff from jTraverser to jdevices, jTraverser does not make use of them. I will do it next week, after I have finished preparing the MARTe stuff for Josh. I am looking forward to using jTraverser2 that may become the default tool for MDSplus. One thing however:  when openng a pulse file in jTraverser2 the default is readonly, I woild prefer normal because our users would be otherwise confused.

**Comment by zack-vii** [comment]
You missed the point. if we want to keep jtraverer, we need to pack the new devicebean stuff with jtraverser2 as they use the same class names but different content. the files that need to go into jTraverser2 are in java/jdevices/src/jtraverser2/java

**Comment by GabrieleManduchi** [comment]
I am just saying that it is possible to move the java beans stuff for jdevices from jTraverser to jdevices. jTraverser does not need the device beans classes except when issuing a device set-up (just calling <device type>Setup method). The device bean classes will be used privately by jDevices.
Therefore there will be no confilict with jTraverser and jTraverser2 about device setups, both will be using the  jdevices.jar classes.

**Comment by GabrieleManduchi** [comment]
Of course thi will require re-writing some code of the java beans classes that will not use anymore jTraverser classes for writing. 
Now I see the point: for writing and reading in the tree the device bean classes need an abstracton (now they use jTraverser classes).

**Comment by zack-vii** [comment]
no there will be a conflict as you will have two files each. one that works with jtraverser and one that works with jtraverser2.
Device* (jt) and Device* (jt2)

**Comment by GabrieleManduchi** [comment]
Ok, I need to look a little into them. We may think of a a common interface to be implemented by jTraverser and jTraverser2. Such an object will be passed to device beans classes for interacting with the pulse file. In any case some cleaning of the device bean classes is needed.

**Comment by zack-vii** [comment]
well we could also solve this with abstract classes

**Comment by GabrieleManduchi** [comment]
exactly. Next week I plan to do this exercise in jTraverser, i.e. cleaning the device beans classes and using such an object for tree operation. Once it has been made, it suffices providing a different implementation/subclass for jTraverser2 and then there would be no incompatibilities.

**Comment by zack-vii** [comment]
Then please investigate the Devcie* adaptations for jtraverser2. so you can draw the line for the interface as close to the devicebeans as possible. e.g. use int typed nids, and keep in mind that subtree holds both the context and the api but i guess we can solve this by iterating over the interface next week

**Comment by GabrieleManduchi** [comment]
Ok, give me a few days for finishing the marte stuff, and then I will work on it. Not getting bored even if locked........

**Comment by zack-vii** [comment]
#1977 paves the way for the pydevices

**Comment by zack-vii** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
I am now working on a first re-organzation of jTraverser representing the first step towards the jTraverser-independent device beans (and device forms) implementation. In this step a java interface (TreeInterface.java) is being defined that defines all the data access operations. In this first implementation, this interface relies on MDSplus.Data objects, not to access the tree (left to the TreeInterface implementation) but to provide a generic container for data to be used by device beans.  We shall discuss later if this is the best solution or if there other ways to represent data to be read/written by device beans. 
I would like to merge this version into alpha (when it will be ready, after rebasing it on alpha) before proceeding to the next step, that is the separation in a new directory of all the device beans stuff that will be independent from jTraverser.

**Comment by zack-vii** [comment]
Can we remove teh DeviceBeans.jar as it is a copy of jTraverser.jar on can use that instead

**Comment by zack-vii** [comment]
I dont think we need to EXPOSE Data as we could have getFloatArray(Object) methods in the interface. the devicebeans only know Strings for expressions and raw arrays float[] int[] etc. for data.
nids may be exposed as Object as well or int if needed. all api functionality should be hidden in the interface.

**Comment by GabrieleManduchi** [comment]
DeviceBeans.jar is currently a copy of jTraverser, but it will be a self-consistent jar containing only the device beans. It is required by netbeans for building Device forms. DeviceBeans.jar should be mainained, or it will break the netbeans applications people use here for building device forms, that are configured using that jar.

**Comment by GabrieleManduchi** [comment]
Do you mean that when reading some composite data from the interface, such as an action or a signal, you get the decompiled version? And viceversa?

**Comment by GabrieleManduchi** [comment]
for nids no problem, they are already int

**Comment by GabrieleManduchi** [comment]
plus getInt() and getFloat() for other operations such as displaying a waveform?

**Comment by zack-vii** [comment]
> 
> 
> Do you mean that when reading some composite data from the interface, such as an action or a signal, you get the decompiled version? And viceversa?

YEs since in teh end it is put in a TextEdit form anyway

**Comment by GabrieleManduchi** [comment]
Ok, I will do so

**Comment by zack-vii** [comment]
> plus getInt() and getFloat() for other operations such as displaying a waveform?

correct. well for the datatypes we need. Its probably copy and paste to do it for all native ones. 
each in their Scalar and Array form and String.

**Comment by zack-vii** [comment]
> DeviceBeans.jar is currently a copy of jTraverser, but it will be a self-consistent jar containing only the device beans. It is required by netbeans for building Device forms. DeviceBeans.jar should be mainained, or it will break the netbeans applications people use here for building device forms, that are configured using that jar.

It should be build in jDevices then.

nothing breaks if they would use jTraverser.jar instead of DeviceBeans.jar right. or is the name important.

**Comment by GabrieleManduchi** [comment]
If you change the name, you need to change the configuration of all the netbeans builder tools people use here..... DeviceBeans.jar will be eventually a jar containing only the device beans, not the devices themselves. It is a jar that is fed to netbeans.

**Comment by zack-vii** [comment]
This can be handled via a mklink though

**Comment by GabrieleManduchi** [comment]
Most people use it on Windows. It makes sense to keep it: it is (it will be) the minimal jar that is required by netbeans.

**Comment by zack-vii** [comment]
so what does it need atm if it does not need anything from jtraverser
or does it only need teh Device* classes

**Comment by zack-vii** [comment]
will that become the interface ... it currently does not contain any DEvice class as those are in jDevcies.

**Comment by GabrieleManduchi** [comment]
The java beans contain methods that are intended to be called only by a Java builder tool as Netbeans

**Comment by GabrieleManduchi** [comment]
Those methods are used by the java IDE for building device forms

**Comment by GabrieleManduchi** [comment]
At the same time those bean object will build up the components of device forms in jdevices

**Comment by GabrieleManduchi** [comment]
That's why they should live in a separate jar

**Comment by zack-vii** [comment]
So the Device*.java modules that are listed in Manifest

**Comment by GabrieleManduchi** [comment]
The beans that are known by the IDE are declared in the Manifest

**Comment by zack-vii** [comment]
I changed it to use ln to link the file so on linux systems it will be just a symbolic link.. on windows it should be what it was before we implemented make-jars. RP #2022

**Comment by GabrieleManduchi** [comment]
For now ok, but it will be again a separate jar when device beans will be hosted in a separate directory (other than jtraverser and jdevices)

**Comment by zack-vii** [comment]
sure, but i figured i weave it in as i was fixing the build scripts for windows anyway. so HerveAncher can move on. If you have a minute can you review the PR and then we should rebase

**Comment by zack-vii** [comment]
I rebased the upstream branch. jtraverser java files should be unaffected though

**Comment by GabrieleManduchi** [comment]
I am working on a separate branch affecting only jTraverser and mdsobjects java. I will rebase it to the current alpha before issuing a PR (I need some days more)

**Comment by zack-vii** [comment]
@GabrieleManduchi : i used your branch gm-new-jtraverser and adapted teh interface to meet the requirements for maven and jtraverser2. also I removed the dependence of DeviceBeans and use reflection instead. this way devicebeans is more a plugin. we need to update the caller scripts, no?

**Comment by GabrieleManduchi** [comment]
They have already been changed (for jTraverser, CompileTree, DecompileTree, jDispatcherIp)

**Comment by GabrieleManduchi** [comment]
If you commit your changes in the branch, I can try it here

**Comment by zack-vii** [comment]
this one is compete but the scripts for jtraverser2 then.

**Comment by zack-vii** [comment]
hm you missed *.bat for windows

**Comment by GabrieleManduchi** [comment]
The directory and Makefile.am for DeviceBeans have been made, not sure I added DeviceBeans  in the main make

**Comment by GabrieleManduchi** [comment]
Oh  now I read better....yes, I did not add the .bat yet

**Comment by zack-vii** [comment]
I think this is it then ready for testing.

**Comment by zack-vii** [comment]
the windows installer should update soon and will be available in https://mdsplus.org/dist/release/Windows/zck_jt2_devb/MDSplus-zck_jt2_devb-7.105-3.exe

**Comment by zack-vii** [comment]
I messed up the batch files but rest should work

**Comment by zack-vii** [comment]
Great I tested jTraverser2 and jTraverser with DEMOADC on Windows and it works.

**Comment by zack-vii** [comment]
mdsobjects was missing get/setNciFlags i co9mmented it out and replace4d it with a java implementation.. you may switch back to native code onch mdsobjects is fixed. but maybe this could be done in a subsequent PR.

**Review by GabrieleManduchi — APPROVED** [review]

**Pull request merged**
