### PR TITLE
Fix: fc32 werrors stable

### LINKED ISSUE #2162: Multiple definition of `Crate` and `Module` in `libCamShr.so` (GCC 10 -fno-common)
Hi All,

I'm trying to compile MDSplus from source (trying to make an AUR package on arch linux). Compilation goes mostly fine with these commands:

```bash
autoreconf -fi -I m4
./configure
make
```

but during make a code issue pops up
(on stable version 7.96.14-7.9.11 at least)

```
gcc -Wall -Wextra  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fvisibility=hidden  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fpic -shared-libgcc -fsigned-char -fno-strict-aliasing  -I/home/daan/Projects/AUR/mdsplus/src/MDSplus/include -I/home/daan/Projects/AUR/mdsplus/src/MDSplus/include -D_FORTIFY_SOURCE=2 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -m64 -shared  -nostartfiles -Wl,-soname=libCamShr.so -o /home/daan/Projects/AUR/mdsplus/src/MDSplus/lib64/libCamShr.so.1.8 add_entry.o bisearch.o cam_functions.o check_for_file.o check_sema4.o commit_entry.o compare_str.o copy.o create_sema4.o create_tmp_file.o debug.o expand_db.o get_crate_status.o get_db_file_size.o get_file_count.o get_file_name.o get_scsi_device_number.o global.o issort.o lock_file.o lookup_entry.o map_data_file.o map_scsi_device.o msg.o parse_crate_db.o parse_cts_db.o QueryHighwayType.o remove_entry.o scsi_io.o ScsiSystemStatus.o turn_crate_on_off_line.o unlock_file.o xlate_logicalname.o RemCamMulti.o RemCamSingle.o RemCamIosb.o -L/home/daan/Projects/AUR/mdsplus/src/MDSplus/lib64/ -lMdsShr -lMdsIpShr 
/bin/ld: bisearch.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: bisearch.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: cam_functions.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: cam_functions.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: check_for_file.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: check_for_file.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: check_sema4.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: check_sema4.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: commit_entry.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: commit_entry.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: compare_str.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: compare_str.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: copy.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: copy.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: create_sema4.o:(.bss+0x10): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: create_sema4.o:(.bss+0x40): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: create_tmp_file.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: create_tmp_file.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: debug.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: debug.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: expand_db.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: expand_db.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: get_crate_status.o:(.bss+0x0): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: get_crate_status.o:(.bss+0x60): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: get_db_file_size.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: get_db_file_size.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: get_file_count.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: get_file_count.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: get_file_name.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: get_file_name.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: get_scsi_device_number.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: get_scsi_device_number.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: lock_file.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: lock_file.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: lookup_entry.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: lookup_entry.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: map_data_file.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: map_data_file.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: map_scsi_device.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: map_scsi_device.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: parse_crate_db.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: parse_crate_db.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: parse_cts_db.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: parse_cts_db.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: QueryHighwayType.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: QueryHighwayType.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: remove_entry.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: remove_entry.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: ScsiSystemStatus.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: ScsiSystemStatus.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: turn_crate_on_off_line.o:(.bss+0x0): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: turn_crate_on_off_line.o:(.bss+0x60): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: unlock_file.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: unlock_file.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
/bin/ld: xlate_logicalname.o:(.bss+0x0): multiple definition of `Crate'; add_entry.o:(.bss+0x0): first defined here
/bin/ld: xlate_logicalname.o:(.bss+0x20): multiple definition of `Module'; add_entry.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:101: /home/daan/Projects/AUR/mdsplus/src/MDSplus/lib64/libCamShr.so] Error 1
```
Can someone comment?
Perhaps this is a known issue which is circumvented through build flags?

### PR DESCRIPTION
**Pull request by zack-vii**
fixes #2162 ; tested on fc32
fixes to satisfy gcc10 and python3.8 on ubuntu20 fc32

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Review by joshStillerman — DISMISSED** [review]
Can you look at my latest slack ?

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
