### PR TITLE
Feature: command tabcompletion for tditest

### PR DESCRIPTION
**Pull request by zack-vii**
uses new findfile and tab completion of readline to add command completion to tditest

### CODE REVIEW

**Review by joshStillerman — COMMENTED** [review]
I built this on Ubuntu18
when I ran it, I ran 
tidttest
I typed Tree<tab> 
and my process and terminal locked up.

**Comment by zack-vii** [comment]
hmm could be because i rebased it down from #1562 i will double check

**Comment by zack-vii** [comment]
Are you sure it locked up and not just showed no result. i programmed it the way that you need to use lower case for .tdi and .py functions and uppercase for builtins.
tree\<tab\> should show treeopen, treeclose, etc.
TR\<tab\> should show TRANSFER, TRANSLATE, etc

**Comment by zack-vii** [comment]
```bash
groups: cannot find name for group ID 1000
I have no name!@Ubuntu18:~/tests/64/mdsobjects/python/tests$ tditest
tree
tree_from_tag(         treedirname(           treeflushoff(          treeopennew(           treesetnciitm(
treeabspath(           treefilename(          treeflushreset(        treeput(               treesetsource(
treeaddnode(           treefindnodetags(      treegetcurrentshot(    treeputrecord(         treeturnoff(
treeaddtag(            treefindnodetagsjeff(  treegetrecord(         treequit(              treeturnon(
treeclose(             treefindnodewild(      treegetsource(         treesetcurrentshot(    treewrite(
treecreatepulsefile(   treefindtagend(        treeopen(              treesetdbiitm(
treedeletepulsefile(   treefindtagwild(       treeopenedit(          treesetdefault(
tree
TR
TRANSFER(       TRANSLATE(      TRANSPOSE_(     TRANSPOSE_MUL(  TRIM(
TR
```
Could you check the MDS_PATH env?

**Comment by joshStillerman** [comment]
It completely locked I'll do a few more tests tomorrowOn Feb 19, 2019 7:19 PM, Timo Schroeder <notifications@github.com> wrote:Are you sure it locked up and just did not show a result. i programmed it the way that you need to use lower case for .tdi and .py functions and uppercase for builtins.
tree should show treeopen, treeclose, etc.
TR should show TRANSFER, TRANSLATE, etc

**Comment by zack-vii** [comment]
any luck on the gdb investigation concerning the hanging process?

**Comment by joshStillerman** [comment]
If my tdipath is simple (one clause) it works fine.  If It is a list (at least my list) it hangs.  I will try to GDB it tomorrow.

My MDS_PATH is:
```
Last login: Tue Feb 26 14:34:40 on ttys010
JoshuasMacBook5:NDM jas$ ssh cmodws102.psfc.mit.edu
Last login: Thu Feb 28 18:28:53 2019 from 74.104.162.53
[jas@cmodws102 ~]$ echo $MDS_PATH 
/usr/local/cmod/tdi;/usr/local/mdsplus/tdi
```

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
