### PR TITLE
Update D3D TDI function after languishing for a while

### PR DESCRIPTION
**Pull request by margomw**
This is the up-to-date TDI functions that are currently being used at GA's new cluster

### CODE REVIEW

**Comment by tfredian** [comment]
This is an automated comment because the author of the PR is not a member of the MDSplus core development team. Can one of the core team members verify this patch and add a comment containing "ok-to-test" (without the hyphens) to the PR if it appears legitimate.

**Comment by zack-vii** [comment]
you need to update deploy/packaging/{redhat,debian}/kernel.noarch

**Comment by margomw** [comment]
@zack-vii 

I have updated the files you asked

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
ok to test

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
test this please

**Comment by tfredian** [comment]
We're having trouble with triggering tests with Jenkins. Disregard all these test comments.

retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
ok to test

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
jenkins test

**Comment by tfredian** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by tfredian — APPROVED** [review]

**Pull request merged**
