### PR TITLE
Gm devices

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Minor changes to RFX devices

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please
missing librealine

**Comment by joshStillerman** [comment]
retest this please
(built without mac, now using it to test mac build)

**Comment by joshStillerman** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Review by AndreaRigoni — APPROVED** [review]

**Pull request merged**
