### PR TITLE
Gm streaming

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Added method stream() to python class Event
Minor fixes to node.js server and to the html page

### CODE REVIEW

**Comment by tfredian** [comment]
Would it be too complicated to send MDSplus serialized data in the STREAMING event? If the consumer could deserialize the data it would be much more efficient (network and cpu) than converting the data to strings, sending, and converting back. The STREAMING event could even send a dictionary or list object containing the signal name, shot, times and values.

**Comment by tfredian** [comment]
The advantage of sending serialized data would depend highly on the typical size of streaming data packets.

**Review by tfredian — APPROVED** [review]
This is fine unless sending serialized data is a better option.

**Comment by GabrieleManduchi** [comment]
The MDS event payload is going to be received by a JavaScript program (Node.js). That's why the data packed is converted in ASCII. In any case the packet is composed of one or few samples since the streaming is for visualization

**Pull request merged**
