### PR TITLE
Fix parsing of tag names in TreeFindNodeWild

### PR DESCRIPTION
**Pull request by merlea**
The maximum length for a tag name is 24 but the lexer in `TreeFindNodeWild` was only matching the first 23 characters.

Proposing this change to solve #2821.

### CODE REVIEW

**Comment by mwinkel-dev** [comment]
Retest this please.

(That request is to the Jenkins build system, not to merlea.)

**Comment by mwinkel-dev** [comment]
Retest this please.

**Comment by mwinkel-dev** [comment]
This PR is second in line to be merged.   First is PR #2817.

**Comment by joshStillerman** [comment]
Retest this please.

**Comment by joshStillerman** [comment]
Retest this please

**Comment by merlea** [comment]
It seems the checks have failed and I don't have access to your Jenkins website. Is it just because this branch is not up-to-date anymore or is it another more serious issue?

**Comment by joshStillerman** [comment]
Retest this please

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
