### PR TITLE
REVIEW REQUIRED! Big renaming of all of the config.h includes

### PR DESCRIPTION
**Pull request by kgerickson**
This is the big rename change that will move all of the #include<config.h> lines to instead be #include <mdsplus/config.h>.  This does two things... 1) It moves the generated header into include/mdsplus, and 2) it renames it.  This is the simple change.  The more complicated one would be not having to install mdsconfig.h at all, but we aren't there yet.  Baby steps :)

This needs some review.  I noticed about a dozen places where we had code that generated C code that included config.h.  I don't know if I got them all.

### CODE REVIEW

**Comment by tfredian** [comment]
ok to test

**Comment by tfredian** [comment]
It looks like there are config.h includes in some of the tests that still need to be fixed.

**Comment by kgerickson** [comment]
Updates pushed

**Review by tfredian — APPROVED** [review]
Looks good to me.

**Pull request merged**
