### PR TITLE
project: threadsafe tdi

### PR DESCRIPTION
**Pull request by zack-vii**
attempt to make tdi threadsafe with lesser use of locks

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
The issue seems to be that tdi does not deep copy data on TdiGetIdent when handling public var. This is probably what you would want for performance but this prevents tdi from being thread safe.
workaround would be to deepcopy publics, possibly add a CONST modifier (used like PUBLIC or P
PRIVATE) to the var makeing it readonly but allows to read the var without deepcopy.
```tdi
CONST PUBLIC _const = myconst()
PUBLIC _const = 123
%TDI-E-CONST cannot modify a constant var
```

**Comment by zack-vii** [comment]
down to one segfault that only occurs on alpine 64x?

**Review by tfredian — APPROVED** [review]
looks good

**Pull request merged**
