### PR TITLE
Feature: Add error reporting in SendMdsMsg

### PR DESCRIPTION
**Pull request by tfredian**
This will add some error reporting for failures occurring when
send messages to mdsip servers. This should provide more information
when diagnosing mdsip communication errors.

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
Tom, if I am not wrong, if for any reason send returns always 0 the program enters an infinite loop because in this case tries is never increased.

**Comment by tfredian** [comment]
I changed the code to only reset tries to 0 if send returns > 0.

**Comment by GabrieleManduchi** [comment]
Yes, but it seems to me that if send keeps on returning 0, tries is never increased......am I wrong?

**Comment by tfredian** [comment]
oops. ok I think I got it now.

**Review by GabrieleManduchi — APPROVED** [review]

**Pull request merged**
