### PR TITLE
Feature: Apply clang-format to all .c, .h, .cpp

### PR DESCRIPTION
**Pull request by joshStillerman**
This PR applies clang-format to all of the rest of the c and c++
source files in mdsplus.

For now it uses the default llvm formatting.
This breaks instances where both
  windows.h
and
  winsock2.h
are included.  (winsock2.h has to be first)
in theory a .clang-format file specifying the 'priority' of regexes
of the includes could prevent this.

I ran the default config, and checked for this case by hand.

### CODE REVIEW

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Comment by joshStillerman** [comment]
retest this please

**Review by zack-vii — APPROVED** [review]
Well i assume you only did the clang filter.. tests say its great.. what should go wrong

**Pull request merged**
