### PR TITLE
Feature: mdsplus-api without JavaMdsLib

### PR DESCRIPTION
**Pull request by zack-vii**
Inspired by issue #1538 i removed the jni entirely and replaced its purpose with "mdspi -P tunnel"
In the process several memcheck and helgrind issues were found and fixed.
TODO: fix lock-order issue between tdivar and tdicompile locks
http://jenkins2.mdsplus.org/job/fc25/4521/

TODO2: javamds,java/mdsobjects MdsTreeTest and MdsTreeNodeTest have memory issies, e.g. Tree does not free Dbid

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by AndreaRigoni** [comment]
Hi Timo! If you look at your mdsplus fork you should have a pull request 12 with the leak fixed 
I'm not in the review list so I will leave it to someone else :-)

cheers

**Review by AndreaRigoni — APPROVED** [review]
OK, great job Timo !

**Comment by zack-vii** [comment]
megerd as part of RP #1866

**Pull request closed without merging**
