### PR TITLE
Feature:new SPIDER devices

### PR DESCRIPTION
**Pull request by GabrieleManduchi**

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Review by AndreaRigoni — DISMISSED** [review]

**Review by zack-vii — DISMISSED** [review]
Your changes are note python 3 compatible.. thats why the tests fail..

### interface ###
Error importing from CRIO_FAU.py: invalid syntax (CRIO_FAU.py, line 75)
Traceback (most recent call last):
  File "/git/mdsplus/python/RfxDevices/__init__.py", line 38, in _mimport
    module = __import__(name, globals())
ModuleNotFoundError: No module named 'CRIO_FAU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/git/mdsplus/tdi/dev_support/MDSDEVICES.py", line 69, in MDSDEVICES
    ans += importDevices(module)
  File "/git/mdsplus/tdi/dev_support/MDSDEVICES.py", line 40, in importDevices
    module = __import__(name)
  File "/git/mdsplus/python/RfxDevices/__init__.py", line 64, in <module>
    _mimport(filename[:-3])
  File "/git/mdsplus/python/RfxDevices/__init__.py", line 40, in _mimport
    module = __import__(name, globals(), level=level)
  File "/git/mdsplus/python/RfxDevices/CRIO_FAU.py", line 75
    print str(e)
            ^
SyntaxError: invalid syntax

**Review by AndreaRigoni — DISMISSED** [review]

**Comment by GabrieleManduchi** [comment]
> Your changes are note python 3 compatible.. thats why the tests fail..
> 
> ### interface
> Error importing from CRIO_FAU.py: invalid syntax (CRIO_FAU.py, line 75)
> Traceback (most recent call last):
> File "/git/mdsplus/python/RfxDevices/**init**.py", line 38, in _mimport
> module = **import**(name, globals())
> ModuleNotFoundError: No module named 'CRIO_FAU'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/git/mdsplus/tdi/dev_support/MDSDEVICES.py", line 69, in MDSDEVICES
> ans += importDevices(module)
> File "/git/mdsplus/tdi/dev_support/MDSDEVICES.py", line 40, in importDevices
> module = **import**(name)
> File "/git/mdsplus/python/RfxDevices/**init**.py", line 64, in
> _mimport(filename[:-3])
> File "/git/mdsplus/python/RfxDevices/**init**.py", line 40, in _mimport
> module = **import**(name, globals(), level=level)
> File "/git/mdsplus/python/RfxDevices/CRIO_FAU.py", line 75
> print str(e)
> ^
> SyntaxError: invalid syntax



> Your changes are note python 3 compatible.. thats why the tests fail..
> 
> ### interface
> Error importing from CRIO_FAU.py: invalid syntax (CRIO_FAU.py, line 75)
> Traceback (most recent call last):
> File "/git/mdsplus/python/RfxDevices/**init**.py", line 38, in _mimport
> module = **import**(name, globals())
> ModuleNotFoundError: No module named 'CRIO_FAU'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/git/mdsplus/tdi/dev_support/MDSDEVICES.py", line 69, in MDSDEVICES
> ans += importDevices(module)
> File "/git/mdsplus/tdi/dev_support/MDSDEVICES.py", line 40, in importDevices
> module = **import**(name)
> File "/git/mdsplus/python/RfxDevices/**init**.py", line 64, in
> _mimport(filename[:-3])
> File "/git/mdsplus/python/RfxDevices/**init**.py", line 40, in _mimport
> module = **import**(name, globals(), level=level)
> File "/git/mdsplus/python/RfxDevices/CRIO_FAU.py", line 75
> print str(e)
> ^
> SyntaxError: invalid syntax

corrected

**Comment by GabrieleManduchi** [comment]
mi sono rotto!!!!!!!!

**Review by AndreaRigoni — APPROVED** [review]

**Pull request merged**
