### PR TITLE
Zck win socket timeout

### PR DESCRIPTION
**Pull request by zack-vii**
should work but mdsdtcl is still reporting 

TCL> dispatch/command/server=localhost:8100 type test
TCL> dispatch/command/server=localhost:8100 type test
Dispatcher select loop failed
Last client addr = 127.0.0.1
TCL>

### CODE REVIEW

**Comment by zack-vii** [comment]
looks like we were lazy with select most of the time
nfds should be the largest file identifier in the list +1
We used FD_SETSIZE which is 64 under windows but sockets can surely have an id larger than that.

MS says the parameter is ignored, though.

Anyway, big bug was that fds under windows are of type SOCKET aka. (void*) under linux they are int. in some functions the mapping was wrong and only set the first 4 bytes of the SOCKET.
In return Connections from Windows could not be reused.

**Comment by zack-vii** [comment]
there are more bug to it

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
could be good now

**Review by tfredian — APPROVED** [review]

**Pull request merged**
