### PR TITLE
Fix: Use junit maven with java classes and apps

### PR DESCRIPTION
**Pull request by zack-vii**
* updates jtraverser2 (bugfixes and features)
* reorganizes java projects in ./java and unifies their Makefile (except jscope)
* enables junit framework for java projects
* implements junit for mdsplus-api (api part or jtraverser2)
* further changed structure of src folders to go together with maven
* added access to the maven publish goal for future publication on maven
  https://search.maven.org/search?q=g:org.mdsplus
  https://oss.sonatype.org/content/repositories/snapshots/org/mdsplus/mdsplus-api

### CODE REVIEW

**Comment by tfredian** [comment]
retest this please

**Comment by zack-vii** [comment]
unfortunately, I think this is a real thing. something in MdsDescrToCstring but I am not sure yet why.
maybe a descriptor that I pass from within java code or its a null string that needs to be honored with a if length==0.

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
retest this please

**Comment by tfredian** [comment]
retest this please

**Review by tfredian — APPROVED** [review]
Looks ok. With only 1228 files changed what could go wrong? ;-)
I actually reviewed all the changes which was quite tedious. The bulk of the "changes" were caused by reorganization of the java code directory structures and the changes to m4's, configure.ac and all the Makefiles.in.

**Comment by zack-vii** [comment]
this includes pr #1754 .
@AndreaRigoni @GabrieleManduchi : Do we have your blessings on this one?

**Comment by tfredian** [comment]
Timo, Josh and I discussed the advantage of doing squash and merges for all pull requests. I changed the settings on mdsplus to only allow squash and merge. The commit title then uses the PR title and the commit comment uses the first comment in the PR. I changed your PR title to conform to our naming scheme. I made it a FIX instead of simply a BUILD since you had some fix commits. Can you edit the PR comment to better describe what all this PR entails including some mention of the fixes applied over and above the main purpose of the PR?

**Pull request merged**
