### PR TITLE
Gm marte2 devices

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
A fix to MARTE2_COMPONENT and two new MARTe2 devices (MARTE2_NI6723 and MARTE2_NI6255)

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by zack-vii** [comment]
so is this now dead?

**Comment by GabrieleManduchi** [comment]
looking at the dates I would say yes

**Pull request closed without merging**
