### PR TITLE
change python setup to work with newer setuptools

### PR DESCRIPTION
**Pull request by dgarnier**
When installing MDSplus with newer setuptools, it refuses to continue do to multiple subdirectories.  More at Issue
https://github.com/MDSplus/mdsplus/issues/2528

### CODE REVIEW

**Review by dgarnier — COMMENTED** [review]
I'm just gonna comment on my own pull request for testing purposes.  Here I'm looking at a particular commit.

**Comment by ModestMC** [comment]
@dgarnier I believe [this PR](https://github.com/MDSplus/mdsplus/pull/2618) might be related to what you're wanting.

**Comment by dgarnier** [comment]
> @dgarnier I believe [this PR](https://github.com/MDSplus/mdsplus/pull/2618) might be related to what you're wanting.

It is, however, I just tested it.. and that PR doesn't actually work for me / needs to be modified & tested.

**Comment by ModestMC** [comment]
> It is, however, I just tested it.. and that PR doesn't actually work for me / needs to be modified & tested.

My main goal was to let you know that other people are interested in having the same stuff addressed, completely get your point regarding it not working. No sense having multiple people come up with independent solutions to the same thing, right?

**Comment by dgarnier** [comment]
I'm closing this pull request in favor of the more complete method of using pyproject.toml used in PR #2698

**Pull request closed without merging**
