### PR TITLE
Build: added support for other visual studio compiler

### PR DESCRIPTION
**Pull request by zack-vii**
@HerveAncher : please check this one out and add the mdsplus/mdsconfig.h header where you have a conflict with \_\_attribute\_\_ stuff. You may find that mdsplus/mdsconfig.h is already included but only if WINDOWS_H is undefined. In that case, please move it out of this condition as it is handled in mdsconfig.h .

### CODE REVIEW

**Comment by HerveAncher** [comment]
@zack-vii I have just cloned your branch on my computer and run it to ensure all is fine.

I still have error during Lex interpretation on these files:
```
yylex/cmdParse.l
Règle de contexte traîné variable à la ligne 60
Règle de contexte traîné variable à la ligne 80
Règle de contexte traîné variable à la ligne 105
Règle de contexte traîné variable à la ligne 115

yylex/mdsdclDeltatimeToSeconds.l
Règle de contexte traîné variable à la ligne 46
```

This is about the asterisk escapement, I need on my system to add a backslash on it to generate properly C files.


In ```mdsdatastreams.cpp``` under Windows, it is not possible to allocate variable without constant size (lines 402 and 410):
```
-char msgBuf[strlen(name) + 256];
+char* msgBuf = new char[strlen(name) + 256];
+delete[] msgBuf;
```
This code is the same as lines 419 and 436.


About the ```visual-studio-build.bat``` Batch, I understand what you mean.
But to support VS2019, I do not know how to deal without introduce the version of compiler and SDK and a way to specify them.
Remember that I compile MDSplus on Windows 10 directly, no Docker, no VM ad no Wine on my case (that is why I absolutely need WIN_PTHREADDIR).

I can create a new file call ```visual-studio-dll.bat``` where I will put my code, but how call it from ```mdsobjects/cpp/Makefile```?
Adding some VS flag in ```configure.ac``` was not a good way?

```VSDLL``` target need to be defined to install DLL, and if I define it with the current config, the Makefile will try to call Wine command.
So I think the using ```@HAVE_WINE_TRUE@``` is the good manner to disable Wine command, and just showing a warning to tell user that somethin is missing (as I did):

```
@HAVE_WINE_TRUE@		for i in $(top_builddir)/defs/*.def; do \
@HAVE_WINE_TRUE@			wine cmd.exe /C "cd @MAKESHLIBDIR@ & @VS_DIR@\\@VS_ARCH@\\bin\\lib /MACHINE:@VS_ARCH@ /DEF:Z:$${deffile////\\}" ; \
@HAVE_WINE_TRUE@		done ;
@HAVE_WINE_TRUE@		wine cmd.exe /C vsbuild @VS_DIR@ @VS_ARCH@ @MAKESHLIBDIR@ ;
@HAVE_WINE_FALSE@		echo "No Wine configuration detected, please install Wine!" ;
```

I this case, I can call ```make``` command without error, call another Windows Batch to generate DLL with Visual Studio 2019, and finally call ```make install```, I did it and it works.


Otherwise, all is fine.

You can merge these modifications and please introduce the points I described above?
Regards.

**Comment by zack-vii** [comment]
The lex stuff are warnings about performance drawbacks. That is normal as those parsers are not optimized.

> I can create a new file call visual-studio-dll.bat where I will put my code, but how call it from mdsobjects/cpp/Makefile?

You dont. Its not meant to be called by the Makefile. It is called when we package the installer in order to include the vs compatible lib files. I your case: Make it a post compile step and just run it directly.

I have woven in your other suggestions though.

**Comment by zack-vii** [comment]
PS it would be great if you could share your project files. we could offer them together with you batch script. to other user that wish to accomplish what you are trying

**Comment by HerveAncher** [comment]
@zack-vii thanks for the 2 commits.

Currently I call these commands to compile under Windows/MinGW-w64 (on your branch):

```
./bootstrap
./configure --disable-valgrind --prefix=/c/IMAS/mdsplus-7.97.0_windows --with-visual-studio
make
cd mdsobjects/cpp
export WIN_PTHREADDIR=C:/vcpkg/installed/x64-windows
export VS_VER=2019
export VC_VER=14.24.28314
export WK_VER=10.0.17134.0
./visual-studio-build.bat "$@"
cd ../..
make install
```

The flag ```--with-visual-studio``` is used without parameter, just to declare it and generate proper elements in Makefile.

Of course, the ```visual-studio-build.bat``` is mine, with ```WIN_PTHREADDIR``` and VS2017/VS2019 management and ```@HAVE_WINE_TRUE@``` trick in ```Makefile.in```

Please find my files in attachment:
[VS2019.zip](https://github.com/MDSplus/mdsplus/files/4298434/VS2019.zip)

**Comment by zack-vii** [comment]
Thanks for the project files. I will work on them once i got some more free time. I am still running VS2017 community. I think assume there is a free (community) release of VS2019. but since it takes some time to install... once the PR are merged i will publish a depersonalized version for users to download in the mdsobjects cpp section of mdsplus.org.

**Comment by HerveAncher** [comment]
Dear @zack-vii what about the files ```mdsdcl/yylex/cmdParse.l``` and ```mdsdcl/yylex/mdsdclDeltatimeToSeconds.l```?

Without the escapement of asterisk character, I cannot compile it under Windows/MinGW, because during the ```./bootstrap``` command, the Lex source files generation failed.

Do you think my adjustments of theses files can be safely integrated to this PR?

**Comment by zack-vii** [comment]
> 
> 
> Dear @zack-vii what about the files `mdsdcl/yylex/cmdParse.l` and `mdsdcl/yylex/mdsdclDeltatimeToSeconds.l`?
> 
> Without the escapement of asterisk character, I cannot compile it under Windows/MinGW, because during the `./bootstrap` command, the Lex source files generation failed.
> 
> Do you think my adjustments of theses files can be safely integrated to this PR?

If you escape the asterix, the parser would look for an actual '*' instead of a variable number of {blanks}. So sorry escaping is not an option as it would break the parsers function. why does your lex fail? which version.

I am addressing the parser issue in PR #1951 

please check if it already fixes mdsdclDeltatimeToSeconds.l. working on cmdParser but it more tricky

**Review by joshStillerman — APPROVED** [review]

**Comment by HerveAncher** [comment]
@zack-vii I have just resync the last alpha branch, the compilation under MinGW is fine and after calling my ```visual-studio-build.bat``` I am able to compile properly additionnal DLL and lib.

The new stable release will be the good one for VS2019!

As you describe, I think getting a specific Windows Batch on MDSplus wiki will be a good manner to allow users doing what I did.

Let me know when this kind of Batch will be available, I will complete my script by adding a wget/curl command to grab the file from wiki.

**Comment by HerveAncher** [comment]
Dear @zack-vii Hi,

I would like to know if you plain to release a new version of MDSplus with the VS2019 support.
I give you my actual [visual-studio-build.bat](https://github.com/MDSplus/mdsplus/files/4556706/visual-studio-build.bat.txt) the one I use from the folder .\mdsobjects\cpp\ to compile lib and DLL for Windows under Windows OS.

You said that putting this version on the MDSplus wiki will be a good solution, I plain to add a link in my README pointing to this file, and explain how to compile MDSplus with VS2019 and [VCPKG](https://github.com/microsoft/vcpkg):

Compile MDSplus sources under MSYS2 MinGW 64-bit terminal:
```
./bootstrap
./configure --disable-valgrind --prefix=/c/IMAS/mdsplus-7.97.0_windows --with-visual-studio
make
```

Call the following command to compile compatible Windows DLL:
```
cd mdsobjects/cpp
export WIN_PTHREADDIR=%VCPKG_DIR%/installed/x64-windows
export VS_VER=2019
export VC_VER=14.25.28610
export WK_VER=10.0.17134.0
./visual-studio-build.bat "$@"
cd ../..
```

And finally install all libraries:
```
make install
```

 You can use these instructions to explain how to proceed on your wiki. Thanks.

**Comment by zack-vii** [comment]
Hi @HerveAncher,

I read this and had a great idea how to get this rolling. Maybe its worth pouring your contribution files in git repository owned by you and with public read access.
You would add mdsplus as a submodule e.g. in
```
./mdsplus
```
put you how-to in
```
./README.md
```
and place the rest of the files, vs project files of the versions you have tested, batch scripts, etc. next to it.
```
./<rest>
```
Then we can link your project on mdsplus.org under user contributions (http://www.mdsplus.org/index.php?title=User_Contrib) and you have full control over your files.
You can even allow pull requests from other users if you wish.

What do you think? Sounds easier for the both of us to maintain. I could help you to get started if you need.

**Comment by HerveAncher** [comment]
Dear @zack-vii,

I have just open an issue: [#2021](https://github.com/MDSplus/mdsplus/issues/2021)
Do you think that this kind of issue should be resolved quickly?

I also need to know if the merge you did about VS2019 build in `alpha_release-7-100-0` should be integrated in the next stable release?

Currently, I need to used alpha branch to compile MDSplus for Windows. I hope to use the stable branch soon.

Regards.

**Comment by zack-vii** [comment]
Hi @HerveAncher,

we will eventually promote alpha to stable... stable does not change oftern if you wish to use stable you may cherry-pick the commit from alpha. Stable is basically an old alpha with some bugfixes on top but we wont merge features or non-essential commits to stable direktly because this may break more the it helps and could make stable unstable.

It is safe to use the alpha branch atm. especially if you are developing yourself as this way you may help shape the current head of MDSplus to work best with your apis.

Personal opinion, stable is overrated and one should only use it when going into operation. better though would be to freeze updates on alpha and run the version you tested.

I will see what i can do about the jTraverser stuff.

Cheers
Timo

**Pull request merged**
