### PR TITLE
Fix: jScope Error Reporting

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Errors raised by mdsip server are now reported in jScope

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Review by AndreaRigoni — APPROVED** [review]
perfect !

**Pull request merged**
