### PR TITLE
Gm marte2 interface

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
New MDSplus Devices for direct MARTe2 interface.  In paritcular, the common superclass MARTE2_COMPONENT can build on the fly the MARTe2 configuration corresponding to the device model

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Review by AndreaRigoni — APPROVED** [review]
Ok for me!

**Pull request merged**
