### PR TITLE
Fix: compiler refactor, resync with bison and flex

### PR DESCRIPTION
**Pull request by zack-vii**
reimplements the lex (flex) yacc (bison) parser generators.
side effect:
* fixes a few compiler bugs: e.g. the missing last char of labels
 label:code was compiled as lebe : code (c.f. tditest/testing/test-tdishr.ans)
* improved parser accuracy due to resolved conflicts
* fixes invalid memory access in TdiGetArgs e.g. when called from Tdi1BuildPath

* the code generators yylex/gen are included in bootstrap.

### CODE REVIEW

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
its done, i think. tdi parser is conflict free and fully reentrant/threadsafe
mdsdcl parser currently used intercative mode with trainling context
```
Variable trailing context rule at line 60
Variable trailing context rule at line 80
Variable trailing context rule at line 105
Variable trailing context rule at line 115
Variable trailing context rules entail a large performance penalty
yylex/mdsdclDeltatimeToSeconds.l
Variable trailing context rule at line 46
Variable trailing context rules entail a large performance penalty
yylex/ocldToXml.l
```
which if omitted would increase performance. maybe later if we feel like it

**Comment by joshStillerman** [comment]
Cool -

   Is your PR ready for review?

**Comment by zack-vii** [comment]
I think so. i am open for discussion.. got to leave now though. post you questions here and i will answer them as soon as i can.. i am on vacation till monday but available at times.

**Comment by zack-vii** [comment]
The last sanitizer isseu has been resolved it seems. ready to go.

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
