### PR TITLE
Feature:added streaming of serialized times and samples

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Allow sending serialized times and samples retaining full back compatibility

### CODE REVIEW

**Comment by zack-vii** [comment]
```
17:05:42 /mdsplus-docker/jenkins/workspace/fc28/src/mdsobjects/cpp/mdsdatastreams.cpp: In static member function 'static void MDSplus::EventStream::send(int, const char*, MDSplus::Data*, MDSplus::Data*)':
17:05:42 /mdsplus-docker/jenkins/workspace/fc28/src/mdsobjects/cpp/mdsdatastreams.cpp:463:12: error: null destination pointer [-Werror=format-overflow=]
17:05:42      sprintf(msgBuf, "%d %s B %d ", shot, name, nTimesSer);
17:05:42      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:05:42 cc1plus: all warnings being treated as errors
```

**Comment by GabrieleManduchi** [comment]
Thanks, unfortunately my local compiler does not issue any warning. Anyway, maybe it wants the passed args explictly initialized, let's see.

**Comment by zack-vii** [comment]
good morning Gabriele: pro tip ;)
ate you using docker. use the picky os and run 
```
deploy/build.sh --os=fc28 --test -i
```
to run it in interactive mode. then you can compile just the file in question as you code.

**Comment by GabrieleManduchi** [comment]
Good tip, I will keep in mind for the next time, thanks!

**Review by AndreaRigoni — APPROVED** [review]
Cool !

**Pull request merged**
