### PR TITLE
typo in constant definitions

### PR DESCRIPTION
**Pull request by zack-vii**

### CODE REVIEW

**Comment by zack-vii** [comment]
failed on

```
No 32-bit support for sanitize=thread. Skipping.

=================================================================

Failure: 64-bit santize with address failed

=================================================================
```

should not be related to the changes.

**Comment by tfredian** [comment]
yes. We're investigating.

**Comment by zack-vii** [comment]
I rebased the branch, just in case

**Comment by zack-vii** [comment]
I assume the test itself or the test environment is buggy.

**Comment by tfredian** [comment]
Turning off the sanitize tests since they seem to be failing when they should not.

**Pull request merged**
