### PR TITLE
Created directory MDSplus_LV2015 with some updates to the LabView interface of MDSObjects. To open discussion with G. Manduchi.

### PR DESCRIPTION
**Pull request by alkhwarizmi**
Improved connectors of "Tree Create.vi" and "Tree Add Node.vi".
Removed useless VI "Tree Create (Mode).vi".
Temptative implementation of "TreeNode Put Timestamped Segment.vi" and "Make Timestamped Segment.vi" to be discussed before finalization.

### CODE REVIEW

**Comment by tfredian** [comment]
Can one of the admins verify this patch?

**Comment by alkhwarizmi** [comment]
Hi Tom,

are you able to switch on alkhwarizmi:alpha-labview-interface without the pull request? (Can I switch on the fork of other developers?)

In this case the pull request is premature, we surey need to do some more work on this.

Sincerely,

**Comment by tfredian** [comment]
Can one of the admins verify this patch?

**Comment by tfredian** [comment]
ok to test

**Comment by alkhwarizmi** [comment]
What's failing? I removed lines containing bare directory names from the Debian version of the package descriptor file.
No idea if this was stopping the build, I can't see the report.
Sincerely,

**Comment by alkhwarizmi** [comment]
No I don't have read access to Jenkins so I can't read reports. I will try to merge the current alpha into my branch. If this does not work it is better that you try to fix t yourself.

**Comment by alkhwarizmi** [comment]
I tried to merge MDSplus/alpha into my branch but it says that everything is up-to-date. I guess you have been faster than me...

Cheers!

**Comment by tfredian** [comment]
retest this please

**Pull request merged**
