### PR TITLE
User level installer for Windows

### PR DESCRIPTION
**Pull request by zack-vii**
# Project goals:
- cleanup windows installation
- enable UserMode installation

### CODE REVIEW

**Comment by zack-vii** [comment]
On Jenkins, fc26 address sanitizer complains about ptrace:
==<pid>==LeakSanitizer has encountered a fatal error.
==<pid>==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==<pid>==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
I cannot reproduce this on my home docker though. ??

=================
fixed by adding --privileged to docker call

**Comment by zack-vii** [comment]
Installer works just fine but the suppression does not

**Comment by zack-vii** [comment]
fc26 takes more than 40 minutes to finish all valgrind and sanitizer tests on 64 and 32 bit. no valgrind issues have been reported in the last build and since the GLIB version on fc26 seems to be buggy anyway we should probably leave the valgrind to fc25 and take advantage of the compiler warnings added by sanitizer.

**Comment by zack-vii** [comment]
retest this please

**Comment by zack-vii** [comment]
RfxDevices MitDevices W7xDevices are missing and python's call results in MDSplusERROR

mayby python3.6 related when handling the string list

**Review by tfredian — APPROVED** [review]
Wow

**Pull request merged**
