### PR TITLE
Revert PR #2620 and PR #2661

### PR DESCRIPTION
**Pull request by WhoBrokeTheBuild**
Revert PR #2620 and PR #2661
This should remove the ability to get APDs over thin client, which should return alpha to stable state (in preparation for cutting a new stable)
We will then work to add these changes back along with additional tests and fixes

### CODE REVIEW

**Review by joshStillerman — DISMISSED** [review]

**Comment by mwinkel-dev** [comment]
I believe this is the full chronology of the APD error cascade . . .

- 9/23/23, PR 2620 = APD stuff
- 10/4/23, Issue 2634 = mentions PR 2620 breaks Python retrieval by tag
- 10/6/23, PR 2632 = v3 IDL (abandoned, never merged) -- had a partial rollback of 2620 to fix tag retrieval
- 10/9/23, PR 2635 = v4 IDL (final OK) -- had a partial rollback of 2620 to fix tag retrieval
- 12/7/23, Issue 2660 = when GA reported that MATLAB can't read signals (RHEL)
- 1/1/24, Issue 2668 = EAST reports duplicate of 2660 (Windows)
- 1/10/24, PR 2661 = extensive fix to APD so that MATLAB isn't broken
- 2/20/24, PR 2716 = (not merged and will be closed) -- when Josh found infinite recursion on cross-version because of APD issues (client: alpha-7-139-66 or -67; server: alpha-7.78.6)
- 2/23/24, PR 2720 = revert of PR 2620 and PR 2661

If the above chronology is correct, then we need to make sure that the reverts leave alpha in this state:
- Python tag retrieval works
- the IDL test harness runs without error
- manual test of MATLAB retrieving a signal works on both Linux and Windows
- no infinite-recursion when client (current alpha) used with old server (alpha-7.78.6)

And also alpha must have these two items needed for DIII-D's campaign that starts in March 2024.
Has PR #2418 because needed by GA (see Issue #2684).
Has PR #2703 because needed by GA (see Issue #2658).

Note: The MATLAB tests are not yet activated in Jenkins, so ignore the status Jenkins reports for MATLAB.

**Comment by mwinkel-dev** [comment]
The `alpha-7.78.6` server was recently upgraded to `alpha-7.139.67`, so was unable to use that server to confirm that this PR eliminates the "infinite recursion" problem when new client connects to old server.   (Will look for another old server or switch to a development VM for that test.)

Manually tested this PR with the following and all passed:
- Python retrieved the `\IP` tag
- ran the IDL test harness
- ran the MATLAB test harness (all tests passed, but will file a new PR to fix a formatting issue)
- MATLAB retrieved / displayed signal on both Ubuntu20 and Windows10
- Issue 2684 (show current with thick-client) is fixed
- Issue 2658 (MdsPut2 compression bug) is fixed, tested on four modes: local, distributed, thick, thin.   Also tested MdsPut() on all four modes.

**Comment by mwinkel-dev** [comment]
As expected, this PR also passes the test for infinite recursion.

Here are the details . . . 
- created an Ubuntu 18 virtual machine
- installed `alpha-7-78-6` on the VM as the mdsip server
- installed `alpha-7-139-67` as the client, and reproduced the bug reported in PR 2716
- installed a manual dev build of this PR as the client, and no recursion occurred

**Review by mwinkel-dev — APPROVED** [review]
Manually compiled and tested the source branch for this PR.   Test results are as per posts on 26 & 27-Feb-2024.

Nonetheless, this is a significant change to the alpha branch.   So would be good for this PR to receive scrutiny from other reviewers too.

**Comment by mwinkel-dev** [comment]
Adding this comment so the following items have references to this PR.

Issues: #2634, #2660, #2668

PRs: #2620, #2632, #2635, #2661, #2716

**Pull request merged**
