### PR TITLE
Fix:recover from return in BASLER camera

### PR DESCRIPTION
**Pull request by GabrieleManduchi**

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by GabrieleManduchi** [comment]
ALway a different failing system!!!!

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by zack-vii** [comment]
worked ;)

**Review by zack-vii — DISMISSED** [review]
I dont get it.. whats the fix here. you simply reverted the whole file away from pep formating it seems. Did you not say it was requiring a return value where it was raising an Exception?

**Comment by GabrieleManduchi** [comment]
Well, it is hard to guess the difference comparing since the two formattings are different. I did not develop this personally, but the developers told me that the current version on the alpha broke the device. Maybe they reported the fixes and the return improvements in another working version. Anyway the currently submitted version works and is python3 compatib;le.

**Comment by GabrieleManduchi** [comment]
Sincerely we cannot afford devoting more time and tests (sessions are ongoing) to start again from the version on alpha and re-fix it.

**Comment by GabrieleManduchi** [comment]
ok, thanks

**Review by AndreaRigoni — APPROVED** [review]

**Pull request merged**
