### PR TITLE
Fix hanging when adding python device by using a python tdi fun to ad…

### PR DESCRIPTION
**Pull request by tfredian**
…d it instead of using the py() tdi fun.

### CODE REVIEW

**Comment by tfredian** [comment]
This should fix this issue: https://github.com/MDSplus/mdsplus/issues/290

**Comment by zack-vii** [comment]
adding a python device does not hang anymore and successfully add the device

**Comment by bstandley** [comment]
Tested to work with MDSTCL, Python, and jTraverser.  The motif-based traverser does not hang but does give an error

> Error adding device instance of ACQ196 from MitDevices: %TREE-E-PARSEERR, Invalid node search string.

but that is not critical for us . . .

**Comment by tfredian** [comment]
The problem with adding a python device via traverser should be fixed now. The traverser use the full path specifier and the DevAddDevice function was putting in an extra backslash at the beginning of the path when using the execute(string). For the python devices it tries to add it without using execute() so the extra backslash was incorrect in that context.

**Pull request merged**
