### PR TITLE
Removing extra writes to stdout [stable]

### PR DESCRIPTION
**Pull request by merlea**
It seems a previous cleanup missed a few writes to stdout.

### CODE REVIEW

**Comment by GabrieleManduchi** [comment]
The same patch has already been reported in alpha, but since those messages area annoying in ITER integrated modeling programs, we can report it directly in stable

**Comment by GabrieleManduchi** [comment]
Tom, how do we proceed? Can you report it directly in stable?

**Comment by merlea** [comment]
Note that the two patches are slightly different, in alpha there is only one such statement removed as the others must have been removed earlier.

**Comment by tfredian** [comment]
Gabriele, I assume your question is related to the: "Can one of the admins verify this patch?"
This message is automatically generated when someone (other than a core MDSplus developer) makes a pull request. Since there is a potential vulnerability with someone putting harmful code into a PR which could be executed during a build and test, a member of the developer team has to simply use a comment on the PR with the phrase "Ok to test". This will cause the PR to be tested and if it passes the test we can approve and merge it.

**Comment by tfredian** [comment]
ok to test

**Review by GabrieleManduchi — APPROVED** [review]

**Pull request merged**
