### PR TITLE
Fix:let no args tdiExecute and tdiCompile in Tree.java

### PR DESCRIPTION
**Pull request by GabrieleManduchi**
Variable args do not handle the case no args

### CODE REVIEW

**Review by zack-vii — COMMENTED** [review]
these functions should not be required as they are covered by the Data... data methods.
calling tree.tdiExceute("$SHOT") should leave data be an empty array of Data just like new Data[0]

**Comment by GabrieleManduchi** [comment]
Unfortunately they are not covered by the Data... arguments. I discovered this just calling tdiCompile with no args.

**Comment by GabrieleManduchi** [comment]
retest this please

**Comment by zack-vii** [comment]
could you check in debug. i use it that way a lot in mdsplus-api. and otherwise this question on SO does not make sense

https://stackoverflow.com/questions/12751746/requiring-at-least-one-element-in-java-variable-argument-list

**Comment by zack-vii** [comment]
calling tdiCompile with no args is an issue as you need at least the String expr.

**Comment by zack-vii** [comment]
Also the unit ttest covers it in
java/mdsobjects/src/test/java/MDSplus/MdsTreeTest.java
DataTest line 36-39

**Review by zack-vii — CHANGES_REQUESTED** [review]
I am not convinced this code duplication is necessary.

**Comment by GabrieleManduchi** [comment]
Really strange, I repeat the tests on my side.........

**Comment by GabrieleManduchi** [comment]
You are right, I discard the PR  I don't know why I got those compilation errors ....

**Pull request closed without merging**
