### PR TITLE
Attempt to fix MdsConnectionTest

### PR DESCRIPTION
**Pull request by WhoBrokeTheBuild**

### CODE REVIEW

**Comment by joshStillerman** [comment]
These are failing on:
```
21:01:06 mkdir -p classes
21:01:06 echo timestamp > classjava.stamp
21:01:06 make[1]: *** No rule to make target '/jars_dir/java/mdsobjects/tests/tests.jar', needed by 'tests.jar'.  Stop.
21:01:06 make[1]: Leaving directory '/workspace/tests/64/java/mdsobjects/tests'
21:01:06 make: *** [Makefile:104: java/mdsobjects/tests] Error 2
```
Is it left over from some debugging step ?

**Comment by zack-vii** [comment]
not sure which one you mean.. it is supposed to be created by the make-jar .. if it is not there the java files could not be compiled. you have to check the main job (1-pull-request) for the logs

**Comment by joshStillerman** [comment]
I think my comment about java timestamps was misplaced here.  I am pretty sure that was about cross-compiling for RP, using  the docker that has already been built.  It just needs to not build the java stuff.

**Comment by joshStillerman** [comment]
retest this please

**Review by joshStillerman — APPROVED** [review]

**Pull request merged**
